import React, { useCallback, useEffect, useMemo, useState } from 'react'
import { Button, Form, Input, InputNumber, Modal, Pagination, Select, Space, Spin, Tag, message } from 'antd'
import { ApartmentOutlined, DeleteOutlined, ReloadOutlined, RobotOutlined, SaveOutlined, TeamOutlined, UserAddOutlined } from '@ant-design/icons'
import ReactFlow, { Background, Controls, MarkerType, type Edge, type Node } from 'reactflow'
import VirtualList from 'rc-virtual-list'
import 'reactflow/dist/style.css'
import type { Character, CharacterDetailContext, CharacterFilterOptions, CharacterGraphPayload, CharacterQueryInput, CharacterStats, PagedResult } from '../../../types'
import { useNovelStore } from '../../../stores/novel.store'
import { getCharacterBatchPreset } from '../../../shared/creation-tools'
import { getFactionNameOptions, getPowerSystemNameOptions, getSpeciesNameOptions, parseWorldRulesJson } from '../../../shared/genre-system'
import { WorkspaceContextSummary, WorkspaceMetric, WorkspacePage, WorkspacePanel, WorkspaceTip } from '../components/WorkspaceShell'
import '../components/boards.css'

interface Props { novelId: number }
interface CharacterFormValues { roleType: Character['roleType']; entityType?: string; species?: string; fullName: string; gender?: string; age?: number; occupation?: string; rankLevel?: string; socialIdentity?: string; background?: string; campFactions: string[]; powerSystems: string[]; contextHooks: string[]; goals?: string; firstImpression?: string; innerConflict?: string; relationshipTension?: string; resonancePoint?: string; characterArc?: string; appearance?: string }
interface CharacterBatchFormValues { majorCount: number; minorCount: number; antagonistCount: number; supportingCount: number; genderRatio?: string; preferredSpecies: string[]; factionBias: string[]; helperRoles: string[]; batchSize: number; specialRequirements?: string }

const PAGE_SIZE = 24
const EMPTY_PAGE: PagedResult<Character> = { items: [], page: 1, pageSize: PAGE_SIZE, total: 0, hasMore: false }
const EMPTY_STATS: CharacterStats = { total: 0, protagonistCount: 0, majorCount: 0, antagonistCount: 0, relationCount: 0, speciesCount: 0 }
const EMPTY_FILTERS: CharacterFilterOptions = { species: [], entityTypes: [] }
const EMPTY_GRAPH: CharacterGraphPayload = { characters: [], relations: [] }
const EMPTY_DETAIL: CharacterDetailContext = { relatedItems: [], relatedCharacters: [], relatedRelations: [] }
const ROLE_META: Record<Character['roleType'], { label: string; color: string }> = { protagonist: { label: '主角', color: 'gold' }, major: { label: '主要人物', color: 'blue' }, minor: { label: '次要人物', color: 'default' }, antagonist: { label: '对立角色', color: 'red' }, supporting: { label: '功能角色', color: 'purple' } }
const ROLE_OPTIONS = [{ value: 'protagonist', label: '主角' }, { value: 'major', label: '主要人物' }, { value: 'antagonist', label: '对立角色' }, { value: 'supporting', label: '功能角色' }, { value: 'minor', label: '次要人物' }] as const
const ENTITY_TYPE_OPTIONS = [{ value: 'human', label: '人类' }, { value: 'undead', label: '亡灵 / 不死者' }, { value: 'beast', label: '兽类 / 灵兽' }, { value: 'immortal', label: '仙神 / 超凡存在' }, { value: 'nonhuman', label: '非人智慧体' }]

function parseStringArray(raw?: string | null): string[] { if (!raw) return []; try { const parsed = JSON.parse(raw); return Array.isArray(parsed) ? parsed.filter((item): item is string => typeof item === 'string').map((item) => item.trim()).filter(Boolean) : [] } catch { return [] } }
function parseAppearance(raw?: string | null): string { if (!raw) return ''; try { const parsed = JSON.parse(raw); return parsed && typeof parsed === 'object' && typeof parsed.description === 'string' ? parsed.description : '' } catch { return '' } }
function toFormValues(character: Character): CharacterFormValues { return { roleType: character.roleType, entityType: character.entityType || '', species: character.species || '', fullName: character.fullName, gender: character.gender || '', age: character.age, occupation: character.occupation || '', rankLevel: character.rankLevel || '', socialIdentity: character.socialIdentity || '', background: character.background || '', campFactions: parseStringArray(character.campFactionIdsJson), powerSystems: parseStringArray(character.powerSystemRefsJson), contextHooks: parseStringArray(character.contextHooksJson), goals: character.goals || '', firstImpression: character.firstImpression || '', innerConflict: character.innerConflict || '', relationshipTension: character.relationshipTension || '', resonancePoint: character.resonancePoint || '', characterArc: character.characterArc || '', appearance: parseAppearance(character.appearanceJson) } }
function serialize(values: CharacterFormValues): Partial<Character> { return { roleType: values.roleType, entityType: values.entityType?.trim() || '', species: values.species?.trim() || '', fullName: values.fullName.trim(), gender: values.gender?.trim() || '', age: values.age, occupation: values.occupation?.trim() || '', rankLevel: values.rankLevel?.trim() || '', socialIdentity: values.socialIdentity?.trim() || '', background: values.background?.trim() || '', campFactionIdsJson: JSON.stringify(values.campFactions || []), powerSystemRefsJson: JSON.stringify(values.powerSystems || []), contextHooksJson: JSON.stringify(values.contextHooks || []), goals: values.goals?.trim() || '', firstImpression: values.firstImpression?.trim() || '', innerConflict: values.innerConflict?.trim() || '', relationshipTension: values.relationshipTension?.trim() || '', resonancePoint: values.resonancePoint?.trim() || '', characterArc: values.characterArc?.trim() || '', appearanceJson: JSON.stringify({ description: values.appearance?.trim() || '' }) } }

export default function CharactersPage({ novelId }: Props) {
  const { currentNovel, setCharacters } = useNovelStore()
  const [form] = Form.useForm<CharacterFormValues>()
  const [batchForm] = Form.useForm<CharacterBatchFormValues>()
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [generating, setGenerating] = useState(false)
  const [pageData, setPageData] = useState<PagedResult<Character>>(EMPTY_PAGE)
  const [stats, setStats] = useState<CharacterStats>(EMPTY_STATS)
  const [filterOptions, setFilterOptions] = useState<CharacterFilterOptions>(EMPTY_FILTERS)
  const [graphData, setGraphData] = useState<CharacterGraphPayload>(EMPTY_GRAPH)
  const [detailContext, setDetailContext] = useState<CharacterDetailContext>(EMPTY_DETAIL)
  const [selectedCharacter, setSelectedCharacter] = useState<Character | null>(null)
  const [selectedId, setSelectedId] = useState<number | null>(null)
  const [creating, setCreating] = useState(false)
  const [batchOpen, setBatchOpen] = useState(false)
  const [page, setPage] = useState(1)
  const [keyword, setKeyword] = useState('')
  const [roleFilter, setRoleFilter] = useState<string>('all')
  const [speciesFilter, setSpeciesFilter] = useState<string>('all')
  const [entityTypeFilter, setEntityTypeFilter] = useState<string>('all')

  const worldRules = useMemo(() => parseWorldRulesJson(currentNovel?.worldRulesJson, currentNovel?.genreName), [currentNovel?.genreName, currentNovel?.worldRulesJson])
  const speciesOptions = useMemo(() => getSpeciesNameOptions(worldRules), [worldRules])
  const factionOptions = useMemo(() => getFactionNameOptions(worldRules), [worldRules])
  const powerSystemOptions = useMemo(() => getPowerSystemNameOptions(worldRules), [worldRules])
  const batchPreset = useMemo(() => getCharacterBatchPreset(currentNovel?.genreName, speciesOptions), [currentNovel?.genreName, speciesOptions])
  const availableSpecies = useMemo(() => Array.from(new Set([...speciesOptions, ...filterOptions.species])).filter(Boolean), [filterOptions.species, speciesOptions])
  const availableEntityTypes = useMemo(() => Array.from(new Set([...ENTITY_TYPE_OPTIONS.map((item) => item.value), ...filterOptions.entityTypes])).filter(Boolean), [filterOptions.entityTypes])
  const buildQuery = useCallback((targetPage = page): CharacterQueryInput => ({ novelId, page: targetPage, pageSize: PAGE_SIZE, ...(roleFilter !== 'all' ? { roleType: roleFilter as Character['roleType'] } : {}), ...(entityTypeFilter !== 'all' ? { entityType: entityTypeFilter } : {}), ...(speciesFilter !== 'all' ? { species: speciesFilter } : {}), ...(keyword.trim() ? { keyword: keyword.trim() } : {}) }), [entityTypeFilter, keyword, novelId, page, roleFilter, speciesFilter])

  const loadCharacterDetail = useCallback(async (characterId: number, seedIds: number[]) => {
    const [character, graph, context] = await Promise.all([
      window.electron.character.get(characterId),
      window.electron.character.getGraph({ novelId, characterIds: seedIds, focusCharacterId: characterId, limit: 24 }),
      window.electron.character.getDetailContext(characterId),
    ])
    if (!character) { setSelectedId(null); setSelectedCharacter(null); setGraphData(EMPTY_GRAPH); setDetailContext(EMPTY_DETAIL); form.resetFields(); return }
    setSelectedId(character.id); setSelectedCharacter(character); setGraphData(graph); setDetailContext(context); form.setFieldsValue(toFormValues(character))
  }, [form, novelId])

  const loadPage = useCallback(async (preferredId?: number | null, targetPage = page) => {
    setLoading(true)
    try {
      const query = buildQuery(targetPage)
      const [list, summary, nextFilters] = await Promise.all([window.electron.character.query(query), window.electron.character.getStats(query), window.electron.character.getFilterOptions(novelId)])
      setPageData(list); setStats(summary); setFilterOptions(nextFilters); setCharacters(list.items)
      const nextId = preferredId ?? (list.items.some((item) => item.id === selectedId) ? selectedId : list.items[0]?.id ?? null)
      if (nextId) { setCreating(false); await loadCharacterDetail(nextId, list.items.map((item) => item.id)) }
      else { setSelectedId(null); setSelectedCharacter(null); setGraphData({ characters: list.items, relations: [] }); setDetailContext(EMPTY_DETAIL); setCreating(false); form.resetFields() }
    } finally { setLoading(false) }
  }, [buildQuery, form, loadCharacterDetail, novelId, page, selectedId, setCharacters])

  useEffect(() => { void loadPage(selectedId, page) }, [loadPage, page])
  useEffect(() => { setPage(1) }, [entityTypeFilter, keyword, roleFilter, speciesFilter])
  useEffect(() => { batchForm.setFieldsValue({ majorCount: batchPreset.majorCount, minorCount: batchPreset.minorCount, antagonistCount: batchPreset.antagonistCount, supportingCount: batchPreset.supportingCount, genderRatio: batchPreset.genderRatio, preferredSpecies: batchPreset.preferredSpecies, factionBias: factionOptions.slice(0, 3), helperRoles: batchPreset.helperRoles, batchSize: 6, specialRequirements: '' }) }, [batchForm, batchPreset, factionOptions])

  const handleNew = () => { setCreating(true); setSelectedId(null); setSelectedCharacter(null); setDetailContext(EMPTY_DETAIL); form.setFieldsValue({ roleType: 'major', entityType: '', species: '', fullName: '', gender: '', age: undefined, occupation: '', rankLevel: '', socialIdentity: '', background: '', campFactions: [], powerSystems: [], contextHooks: [], goals: '', firstImpression: '', innerConflict: '', relationshipTension: '', resonancePoint: '', characterArc: '', appearance: '' }) }
  const handleSave = async () => { const values = await form.validateFields(); setSaving(true); try { if (selectedCharacter?.id) { await window.electron.character.update(selectedCharacter.id, serialize(values)); await loadPage(selectedCharacter.id, page) } else { const nextId = await window.electron.character.create(novelId, serialize(values)); await loadPage(nextId, page) } setCreating(false); message.success('人物档案已保存。') } catch (error) { console.error(error); message.error('保存失败，请稍后再试。') } finally { setSaving(false) } }
  const handleDelete = async () => { if (!selectedCharacter?.id) return; Modal.confirm({ title: `删除「${selectedCharacter.fullName}」？`, content: '删除人物后，不会自动清理时间轴和物品里的关联描述，请确认他不是仍在使用的关键角色。', okButtonProps: { danger: true }, onOk: async () => { await window.electron.character.delete(selectedCharacter.id); await loadPage(null, page); message.success('人物已删除。') } }) }
  const handleGenerateProtagonist = async () => { setGenerating(true); try { const nextId = await window.electron.character.generateProtagonist(novelId, {}); await loadPage(nextId, 1); message.success('主角首版已生成。') } catch (error) { console.error(error); message.error('主角生成失败。') } finally { setGenerating(false) } }
  const handleBatchGenerate = async () => { const values = batchForm.getFieldsValue(); setGenerating(true); try { await window.electron.character.batchGenerate(novelId, values); setBatchOpen(false); await loadPage(null, 1); message.success('人物网络首轮已生成。') } catch (error) { console.error(error); message.error('批量生成人物失败。') } finally { setGenerating(false) } }
  const handleGenerateRelations = async () => { setGenerating(true); try { await window.electron.character.generateRelations(novelId); await loadPage(selectedId, page); message.success('人物关系已补齐首版。') } catch (error) { console.error(error); message.error('人物关系生成失败。') } finally { setGenerating(false) } }
  const handleClear = async () => { Modal.confirm({ title: '清空人物系统？', content: '会删除当前小说下全部人物与关系数据，此操作不可撤销。', okType: 'danger', okText: '确认清空', onOk: async () => { await window.electron.character.clear(novelId); form.resetFields(); setSelectedId(null); setSelectedCharacter(null); setDetailContext(EMPTY_DETAIL); setGraphData(EMPTY_GRAPH); setCreating(false); await loadPage(null, 1); message.success('人物系统已清空。') } }) }

  const selectedLead = selectedCharacter ? selectedCharacter.innerConflict || selectedCharacter.goals || selectedCharacter.firstImpression || selectedCharacter.background || '先补清这个角色眼下最强的目标和卡点。' : creating ? '先定身份、当前目标和与主线的挂点，后面再补细节。' : '先从左侧选中一位角色，或批量生成一版角色网络。'

  return (
    <WorkspacePage className="novel-characters-page" layout="wide" eyebrow="人物系统" title="人物系统" description="角色列表改为分页与虚拟滚动，关系图只展示当前窗口和焦点邻居，长篇下也能稳定回查。" actions={<div className="novel-characters__hero-actions"><div className="novel-characters__hero-actions-group novel-characters__hero-actions-group--primary"><Button type="primary" icon={<TeamOutlined />} loading={generating} onClick={() => setBatchOpen(true)}>AI 批量生成</Button><Button icon={<RobotOutlined />} loading={generating} onClick={handleGenerateProtagonist}>AI 补主角</Button><Button icon={<ApartmentOutlined />} loading={generating} onClick={handleGenerateRelations}>AI 生成关系</Button></div><div className="novel-characters__hero-actions-group"><Button icon={<UserAddOutlined />} onClick={handleNew}>新建人物</Button><Button icon={<ReloadOutlined />} onClick={() => void loadPage(selectedId, page)}>刷新</Button><Button danger icon={<DeleteOutlined />} loading={generating} onClick={() => void handleClear()}>清空人物</Button></div></div>} contextSummary={<WorkspaceContextSummary items={[{ label: '题材', value: currentNovel?.genreName || '未设置' }, { label: '当前筛选总量', value: `${pageData.total} 位` }, { label: '势力 / 体系', value: `${factionOptions.length} 个势力 / ${powerSystemOptions.length} 套体系` }, { label: '当前焦点', value: selectedCharacter ? `${selectedCharacter.fullName} · ${ROLE_META[selectedCharacter.roleType].label}` : '未选中人物' }]} />} metrics={<><WorkspaceMetric label="筛选后角色数" value={stats.total} tone="warm" hint={`当前第 ${pageData.page} 页，每页 ${pageData.pageSize} 位`} /><WorkspaceMetric label="关系窗口" value={graphData.relations.length} hint="只渲染当前页与焦点邻居的关系，避免整网卡死" /><WorkspaceMetric label="种类覆盖" value={stats.speciesCount} tone="cool" hint="当前筛选条件下已出现的种类数" /><WorkspaceMetric label="推荐首轮规模" value={batchPreset.majorCount + batchPreset.antagonistCount + batchPreset.supportingCount + batchPreset.minorCount} hint="按当前题材预设的人物网络规模" /></>} aside={<><WorkspacePanel title="题材人物生态" description={worldRules.characterEcology.overview}><div className="novel-note-list">{worldRules.characterEcology.slots.slice(0, 4).map((slot) => <div key={slot.id} className="novel-note-list__item"><strong>{slot.label}</strong>：{slot.contextLink || slot.narrativeFunction || '建议直接和主线冲突挂钩。'}</div>)}</div></WorkspacePanel><WorkspaceTip title="当前承载方式"><div>列表按页加载，不再一次性把全部角色灌进界面。</div><div>关系图只看当前窗口和焦点邻居，避免大网图失控。</div><div>侧栏关联物品与关系只查当前人物，不全表回扫。</div></WorkspaceTip></>}>
      <WorkspacePanel title="人物关系图" description="图谱只展示当前页角色与选中人物的一阶邻居，点击节点后可直接切到右侧档案。"><CharacterRelationGraph characters={graphData.characters} relations={graphData.relations} selectedId={selectedId} onSelect={(characterId) => void loadCharacterDetail(characterId, pageData.items.map((item) => item.id))} /></WorkspacePanel>
      <div className="novel-split novel-split--sidebar">
        <WorkspacePanel title="人物列表" description="左侧改成查询式列表，支持关键词、角色类型、实体类型和种类筛选。" extra={<div className="novel-filter-bar"><div className="novel-filter-bar__row"><Input.Search allowClear placeholder="搜索姓名、目标、职业或矛盾" value={keyword} onChange={(event) => setKeyword(event.target.value)} onSearch={setKeyword} /><Select value={roleFilter} options={[{ value: 'all', label: '全部角色' }, ...ROLE_OPTIONS]} onChange={setRoleFilter} /></div><div className="novel-filter-bar__row"><Select value={entityTypeFilter} options={[{ value: 'all', label: '全部实体' }, ...availableEntityTypes.map((item) => ({ value: item, label: ENTITY_TYPE_OPTIONS.find((option) => option.value === item)?.label || item }))]} onChange={setEntityTypeFilter} /><Select value={speciesFilter} options={[{ value: 'all', label: '全部种类' }, ...availableSpecies.map((item) => ({ value: item, label: item }))]} onChange={setSpeciesFilter} /></div><div className="novel-filter-bar__summary">当前筛出 {pageData.total} 位人物。建议优先盯住主角、对立角色和功能位。</div></div>}>
          {loading ? <div className="novel-empty"><Spin /></div> : pageData.total === 0 ? <div className="novel-empty">当前筛选下还没有人物，可以放宽筛选，或直接批量生成首版人物网。</div> : <div style={{ display: 'grid', gap: 12 }}><VirtualList data={pageData.items} height={520} itemHeight={120} itemKey="id">{(character: Character) => <button key={character.id} type="button" className={`novel-list-card ${selectedId === character.id ? 'novel-list-card--active' : ''}`} onClick={() => void loadCharacterDetail(character.id, pageData.items.map((item) => item.id))} style={{ textAlign: 'left', cursor: 'pointer' }}><div className="novel-list-card__title">{character.fullName}</div><div className="novel-list-card__meta"><Tag color={ROLE_META[character.roleType].color}>{ROLE_META[character.roleType].label}</Tag>{character.entityType ? <Tag>{ENTITY_TYPE_OPTIONS.find((item) => item.value === character.entityType)?.label || character.entityType}</Tag> : null}{character.species ? <Tag>{character.species}</Tag> : null}{character.rankLevel ? <Tag color="blue">{character.rankLevel}</Tag> : null}</div><div className="novel-list-card__desc">{character.innerConflict || character.goals || character.firstImpression || character.background || '这个角色还没有补出核心矛盾。'}</div></button>}</VirtualList><Pagination current={pageData.page} pageSize={pageData.pageSize} total={pageData.total} size="small" showSizeChanger={false} onChange={setPage} /></div>}
        </WorkspacePanel>
        <WorkspacePanel title={selectedCharacter ? `编辑：${selectedCharacter.fullName}` : creating ? '新建人物' : '人物档案'} description="先写清身份和眼下目标，再补人物与主线、势力和关系网的绑定。" extra={<Space>{selectedCharacter ? <Button danger icon={<DeleteOutlined />} onClick={() => void handleDelete()}>删除</Button> : null}<Button type="primary" icon={<SaveOutlined />} loading={saving} onClick={() => void handleSave()}>保存</Button></Space>}>
          {!selectedCharacter && !creating && !loading ? <div className="novel-empty">左侧选中一个人物后，右侧就能直接编辑。也可以新建，从身份与动机开始补。</div> : <>
            <div className="novel-characters__editor-intro"><div className="novel-characters__editor-intro-copy"><div className="novel-kicker">{selectedCharacter ? '当前人物' : '新建档案'}</div><strong>{selectedCharacter ? selectedCharacter.fullName : '从身份与动机开始补'}</strong><span>{selectedLead}</span></div><div className="novel-characters__editor-stats"><div><label>角色定位</label><strong>{selectedCharacter ? ROLE_META[selectedCharacter.roleType].label : '待定'}</strong></div><div><label>关联关系</label><strong>{selectedCharacter ? detailContext.relatedRelations.length : 0}</strong></div><div><label>关联物品</label><strong>{selectedCharacter ? detailContext.relatedItems.length : 0}</strong></div></div></div>
            <Form form={form} layout="vertical">
              <div className="novel-form-section"><div className="novel-form-section__header"><div className="novel-form-section__title">角色身份</div><div className="novel-form-section__desc">先确定他是什么人、站在哪个位置、用什么名字进场。</div></div><div className="novel-grid novel-grid--3"><Form.Item name="roleType" label="角色类型" rules={[{ required: true, message: '请选择角色类型' }]}><Select options={ROLE_OPTIONS as unknown as Array<{ value: Character['roleType']; label: string }>} /></Form.Item><Form.Item name="entityType" label="实体类型"><Select allowClear options={ENTITY_TYPE_OPTIONS} /></Form.Item><Form.Item name="species" label="种类 / 物种"><Select showSearch allowClear options={availableSpecies.map((item) => ({ value: item, label: item }))} /></Form.Item></div><div className="novel-grid novel-grid--3"><Form.Item name="fullName" label="姓名" rules={[{ required: true, message: '请输入姓名' }]}><Input placeholder="尽量使用正常、可读的人名。" /></Form.Item><Form.Item name="gender" label="性别"><Input /></Form.Item><Form.Item name="age" label="年龄"><InputNumber min={0} style={{ width: '100%' }} /></Form.Item></div><div className="novel-grid novel-grid--3"><Form.Item name="occupation" label="职业 / 身份"><Input /></Form.Item><Form.Item name="rankLevel" label="等级 / 职级"><Input /></Form.Item><Form.Item name="socialIdentity" label="社会位置"><Input /></Form.Item></div></div>
              <div className="novel-form-section"><div className="novel-form-section__header"><div className="novel-form-section__title">阵营与主线挂点</div><div className="novel-form-section__desc">人物不要悬空存在，最好和势力、能力体系与主线问题直接绑定。</div></div><div className="novel-grid novel-grid--2"><Form.Item name="campFactions" label="所属势力"><Select mode="tags" allowClear options={factionOptions.map((item) => ({ value: item, label: item }))} /></Form.Item><Form.Item name="powerSystems" label="关联体系"><Select mode="tags" allowClear options={powerSystemOptions.map((item) => ({ value: item, label: item }))} /></Form.Item></div><Form.Item name="contextHooks" label="与主线的挂点"><Select mode="tags" allowClear placeholder="例如：掌握补给线、知道旧案真相、被关键势力追杀" /></Form.Item><Form.Item name="background" label="背景经历"><Input.TextArea rows={5} placeholder="只写会持续影响这个人物判断和行动的经历。" /></Form.Item></div>
              <div className="novel-form-section"><div className="novel-form-section__header"><div className="novel-form-section__title">动机与张力</div><div className="novel-form-section__desc">目标、内在矛盾和关系张力，是人物真正能写下去的核心。</div></div><div className="novel-grid novel-grid--2"><Form.Item name="goals" label="当前目标"><Input.TextArea rows={4} /></Form.Item><Form.Item name="firstImpression" label="第一印象"><Input.TextArea rows={4} /></Form.Item></div><div className="novel-grid novel-grid--2"><Form.Item name="innerConflict" label="内在矛盾"><Input.TextArea rows={4} /></Form.Item><Form.Item name="relationshipTension" label="关系张力"><Input.TextArea rows={4} /></Form.Item></div></div>
              <div className="novel-form-section"><div className="novel-form-section__header"><div className="novel-form-section__title">可识别特征与后续弧光</div><div className="novel-form-section__desc">人物既要有辨识度，也要给后续变化留空间。</div></div><div className="novel-grid novel-grid--2"><Form.Item name="resonancePoint" label="读者共情点"><Input.TextArea rows={4} /></Form.Item><Form.Item name="characterArc" label="后续弧光"><Input.TextArea rows={4} /></Form.Item></div><Form.Item name="appearance" label="可识别外观"><Input.TextArea rows={4} placeholder="只写辨识度，不要堆满形容词。" /></Form.Item></div>
            </Form>
            {selectedCharacter ? <div className="novel-support-grid" style={{ marginTop: 20 }}><WorkspaceTip title="相关物品">{detailContext.relatedItems.length === 0 ? <div>这个人物还没有绑定关键物品，可以去物品页补上。</div> : detailContext.relatedItems.map((item) => <div key={item.id}>{item.itemName}{item.category ? ` · ${item.category}` : ''}</div>)}</WorkspaceTip><WorkspaceTip title="相关关系">{detailContext.relatedRelations.length === 0 ? <div>这个人物还没有关系链，可以先生成一版关系网络。</div> : detailContext.relatedRelations.map((relation) => { const other = detailContext.relatedCharacters.find((item) => item.id === (relation.charAId === selectedCharacter.id ? relation.charBId : relation.charAId)); return <div key={relation.id}>{other?.fullName || '未知人物'} · {relation.relationLabel || relation.relationType || '关系待补'}</div> })}</WorkspaceTip></div> : null}
          </>}
        </WorkspacePanel>
      </div>
      <Modal title="批量生成人物" open={batchOpen} onCancel={() => setBatchOpen(false)} onOk={() => void handleBatchGenerate()} confirmLoading={generating} okText="开始生成"><Form form={batchForm} layout="vertical"><div className="novel-note-list" style={{ marginBottom: 16 }}><div className="novel-note-list__item">建议先生成主角、主要人物和对立角色，再逐轮补功能位和次要角色。</div><div className="novel-note-list__item">批量阶段先补结构，不要试图一次把每个人写满。</div></div><div className="novel-grid novel-grid--2"><Form.Item name="majorCount" label="主要人物"><Select options={[2, 3, 4, 5, 6].map((value) => ({ value, label: `${value} 位` }))} /></Form.Item><Form.Item name="minorCount" label="次要人物"><Select options={[3, 5, 6, 8, 10].map((value) => ({ value, label: `${value} 位` }))} /></Form.Item></div><div className="novel-grid novel-grid--2"><Form.Item name="antagonistCount" label="对立角色"><Select options={[0, 1, 2, 3].map((value) => ({ value, label: `${value} 位` }))} /></Form.Item><Form.Item name="supportingCount" label="功能角色"><Select options={[0, 1, 2, 3, 4].map((value) => ({ value, label: `${value} 位` }))} /></Form.Item></div><Form.Item name="genderRatio" label="性别与年龄建议"><Input.TextArea rows={3} /></Form.Item><Form.Item name="preferredSpecies" label="优先种类"><Select mode="multiple" allowClear options={availableSpecies.map((item) => ({ value: item, label: item }))} /></Form.Item><Form.Item name="factionBias" label="优先势力来源"><Select mode="multiple" allowClear options={factionOptions.map((item) => ({ value: item, label: item }))} /></Form.Item><Form.Item name="helperRoles" label="优先功能位"><Select mode="tags" allowClear placeholder="例如：队医、情报员、导师、卧底" /></Form.Item><Form.Item name="batchSize" label="每批生成数量"><Select options={[4, 6, 8].map((value) => ({ value, label: `${value} 位 / 批` }))} /></Form.Item><Form.Item name="specialRequirements" label="额外要求"><Input.TextArea rows={4} placeholder="例如：需要一个掌握关键药剂的人、一个和主角有旧债的人。" /></Form.Item></Form></Modal>
    </WorkspacePage>
  )
}

function CharacterRelationGraph({ characters, relations, selectedId, onSelect }: { characters: Character[]; relations: CharacterGraphPayload['relations']; selectedId: number | null; onSelect: (characterId: number) => void }) {
  if (characters.length === 0) return <div className="novel-empty">当前还没有可视化的人物关系，先生成或创建一批角色。</div>
  const roleOrder: Character['roleType'][] = ['protagonist', 'major', 'antagonist', 'supporting', 'minor']
  const nodes: Node[] = roleOrder.flatMap((role, columnIndex) => characters.filter((character) => character.roleType === role).map((character, rowIndex) => ({ id: String(character.id), position: { x: columnIndex * 220, y: rowIndex * 126 }, data: { label: `${character.fullName}\n${ROLE_META[character.roleType].label}` }, draggable: false, selectable: true, style: { width: 168, borderRadius: 18, border: selectedId === character.id ? '2px solid rgba(143, 99, 48, 0.88)' : '1px solid rgba(122, 93, 52, 0.18)', background: selectedId === character.id ? 'linear-gradient(180deg, rgba(246, 202, 124, 0.18), rgba(255,255,255,0.94))' : 'rgba(255,255,255,0.92)', color: '#1e2738', fontSize: 12, lineHeight: 1.6, whiteSpace: 'pre-line', boxShadow: '0 12px 24px rgba(71, 53, 28, 0.08)', padding: '10px 12px' } })))
  const visibleIds = new Set(characters.map((character) => character.id))
  const edges: Edge[] = relations.filter((relation) => visibleIds.has(relation.charAId) && visibleIds.has(relation.charBId)).map((relation) => ({ id: String(relation.id), source: String(relation.charAId), target: String(relation.charBId), label: relation.relationLabel || relation.relationType || '关联', type: 'smoothstep', markerEnd: { type: MarkerType.ArrowClosed, width: 18, height: 18 }, style: { stroke: '#8f6330', strokeWidth: 1.2 }, labelStyle: { fill: '#6f614f', fontSize: 11 } }))
  return <div style={{ height: 520, borderRadius: 22, overflow: 'hidden', border: '1px solid rgba(122, 93, 52, 0.12)', background: 'rgba(255,255,255,0.72)' }}><ReactFlow nodes={nodes} edges={edges} fitView nodesDraggable={false} elementsSelectable panOnDrag zoomOnScroll={false} onNodeClick={(_event, node) => onSelect(Number(node.id))}><Background color="rgba(143, 99, 48, 0.12)" gap={18} /><Controls showInteractive={false} /></ReactFlow></div>
}
