import type { PromptCatalogEntry } from './prompts/prompt-types'
// 统一中文护栏标记：本轮任务焦点 由 prompts/prompt-common.ts 单一来源定义
import { placeholder } from './prompts/prompt-common'
import {
  batchCharacterPrompt,
  characterRelationsPrompt,
  expandBackgroundPrompt,
  mapGenerationPrompt,
  protagonistPrompt,
} from './prompts/asset-prompts'
import {
  buildChapterOutlinePlanningPrompt,
  buildStoryArcPlanningPrompt,
} from './prompts/planning-prompts'
import {
  buildChapterWritingPrompt,
  rewriteParagraphPrompt,
} from './prompts/writing-prompts'
import {
  aiCheckPrompt,
  buildContinuityStatePrompt,
  chapterSummaryPrompt,
  contentScoringPrompt,
} from './prompts/review-prompts'

export * from './prompts/prompt-types'
export {
  sectionUnlessCovered,
  buildVariationHint,
  buildAvoidanceSection,
  HUMAN_LANGUAGE_RULE_LINES,
  buildHumanLanguageRules,
  buildContextAlignmentRules,
  buildGenreRealityRules,
  buildOutputQualityRules,
  buildHumanizedLongformDesignRules,
  GLOBAL_WRITING_RULES,
} from './prompts/prompt-common'
export * from './prompts/asset-prompts'
export * from './prompts/planning-prompts'
export * from './prompts/writing-prompts'
export * from './prompts/review-prompts'

export const PROMPT_CATEGORIES = ['全部', '创作初始化', '人物系统', '大纲规划', '正文编写', '世界构建'] as const

export const PROMPT_CATALOG: PromptCatalogEntry[] = [
  {
    key: 'expandBackground',
    name: '背景扩充',
    description: '扩写开篇设定，生成背景、标题和简介。',
    category: '创作初始化',
    params: [
      { key: 'userBackground', label: '用户背景' },
      { key: 'genre', label: '题材' },
      { key: 'worldTemplateSummary', label: '世界观模板摘要' },
    ],
    template: expandBackgroundPrompt({
      userBackground: placeholder('userBackground'),
      genre: placeholder('genre'),
      worldTemplateSummary: placeholder('worldTemplateSummary'),
    }),
  },
  {
    key: 'protagonist',
    name: '主角生成',
    description: '生成可直接进入后续剧情设计的主角档案。',
    category: '人物系统',
    params: [
      { key: 'novelTitle', label: '小说标题' },
      { key: 'novelSynopsis', label: '小说背景' },
      { key: 'genre', label: '题材' },
      { key: 'worldSummary', label: '世界规则摘要' },
      { key: 'storyCore', label: '故事核心' },
      { key: 'gender', label: '性别' },
      { key: 'surnameHint', label: '姓名方向' },
    ],
    template: protagonistPrompt({
      novelTitle: placeholder('novelTitle'),
      novelSynopsis: placeholder('novelSynopsis'),
      genre: placeholder('genre'),
      worldSummary: placeholder('worldSummary'),
      storyCore: placeholder('storyCore'),
      gender: placeholder('gender'),
      surnameHint: placeholder('surnameHint'),
    }),
  },
  {
    key: 'batchCharacter',
    name: '批量配角生成',
    description: '批量补出能服务主线的配角。',
    category: '人物系统',
    params: [
      { key: 'novelTitle', label: '小说标题' },
      { key: 'novelSynopsis', label: '小说背景' },
      { key: 'protagonistSummary', label: '主角摘要' },
      { key: 'existingNames', label: '已有人名' },
      { key: 'genre', label: '题材' },
      { key: 'worldSummary', label: '世界规则摘要' },
      { key: 'storyCore', label: '故事核心' },
      { key: 'count', label: '数量' },
      { key: 'genderRatio', label: '性别比例' },
      { key: 'specialRequirements', label: '特殊要求' },
    ],
    template: batchCharacterPrompt({
      novelTitle: placeholder('novelTitle'),
      novelSynopsis: placeholder('novelSynopsis'),
      protagonistSummary: placeholder('protagonistSummary'),
      existingNames: placeholder('existingNames'),
      genre: placeholder('genre'),
      worldSummary: placeholder('worldSummary'),
      storyCore: placeholder('storyCore'),
      count: Number.NaN,
      genderRatio: placeholder('genderRatio'),
      specialRequirements: placeholder('specialRequirements'),
    }).replace('NaN', placeholder('count')),
  },
  {
    key: 'characterRelations',
    name: '关系网络生成',
    description: '根据已有角色整理关系网络和张力。',
    category: '人物系统',
    params: [
      { key: 'novelSynopsis', label: '小说背景' },
      { key: 'characterList', label: '人物列表' },
    ],
    template: characterRelationsPrompt({
      novelSynopsis: placeholder('novelSynopsis'),
      characterList: placeholder('characterList'),
    }),
  },
  {
    key: 'storyArcs',
    name: '故事弧规划',
    description: '规划连续推进的故事弧和支线落位。',
    category: '大纲规划',
    params: [
      { key: 'novelTitle', label: '小说标题' },
      { key: 'genre', label: '题材' },
      { key: 'storyGoal', label: '故事目标' },
      { key: 'coreConflict', label: '核心冲突' },
      { key: 'mainPlot', label: '主线剧情' },
      { key: 'subPlots', label: '支线剧情' },
      { key: 'ending', label: '结局方向' },
      { key: 'totalChapters', label: '总章节数' },
      { key: 'rhythmSummary', label: '节奏比例' },
      { key: 'background', label: '背景补充' },
      { key: 'protagonistReference', label: '主角称呼' },
      { key: 'protagonistRule', label: '主角命名规则' },
    ],
    template: buildStoryArcPlanningPrompt({
      novelTitle: placeholder('novelTitle'),
      genre: placeholder('genre'),
      storyGoal: placeholder('storyGoal'),
      coreConflict: placeholder('coreConflict'),
      mainPlot: placeholder('mainPlot'),
      subPlots: placeholder('subPlots'),
      ending: placeholder('ending'),
      totalChapters: Number.NaN,
      rhythmSummary: placeholder('rhythmSummary'),
      background: placeholder('background'),
      protagonistReference: placeholder('protagonistReference'),
      protagonistRule: placeholder('protagonistRule'),
    }).replace('NaN', placeholder('totalChapters')),
  },
  {
    key: 'chapterOutline',
    name: '章节细纲生成',
    description: '为当前故事弧拆出逐章大纲。',
    category: '大纲规划',
    params: [
      { key: 'novelTitle', label: '小说标题' },
      { key: 'genre', label: '题材' },
      { key: 'storyGoal', label: '故事目标' },
      { key: 'coreConflict', label: '核心冲突' },
      { key: 'mainPlot', label: '主线剧情' },
      { key: 'arcName', label: '故事弧名称' },
      { key: 'arcGoal', label: '故事弧目标' },
      { key: 'arcSummary', label: '故事弧概述' },
      { key: 'arcGrowthLedger', label: '成长账本' },
      { key: 'arcCostLedger', label: '代价账本' },
      { key: 'chapterStart', label: '起始章节' },
      { key: 'chapterEnd', label: '结束章节' },
      { key: 'previousSummary', label: '前情摘要' },
      { key: 'characterStates', label: '人物状态' },
      { key: 'continuitySummary', label: '连续性记忆' },
      { key: 'openLoops', label: '未回收事项' },
      { key: 'worldRulesSummary', label: '世界规则摘要' },
      { key: 'protagonistReference', label: '主角称呼' },
      { key: 'protagonistRule', label: '主角命名规则' },
    ],
    template: buildChapterOutlinePlanningPrompt({
      novelTitle: placeholder('novelTitle'),
      genre: placeholder('genre'),
      storyGoal: placeholder('storyGoal'),
      coreConflict: placeholder('coreConflict'),
      mainPlot: placeholder('mainPlot'),
      arcName: placeholder('arcName'),
      arcGoal: placeholder('arcGoal'),
      arcSummary: placeholder('arcSummary'),
      arcGrowthLedger: placeholder('arcGrowthLedger'),
      arcCostLedger: placeholder('arcCostLedger'),
      chapterStart: Number.NaN,
      chapterEnd: Number.NaN,
      previousSummary: placeholder('previousSummary'),
      characterStates: placeholder('characterStates'),
      continuitySummary: placeholder('continuitySummary'),
      openLoops: placeholder('openLoops'),
      worldRulesSummary: placeholder('worldRulesSummary'),
      protagonistReference: placeholder('protagonistReference'),
      protagonistRule: placeholder('protagonistRule'),
    }).replace('NaN', placeholder('chapterStart')).replace('NaN', placeholder('chapterEnd')),
  },
  {
    key: 'chapterWriting',
    name: '正文生成',
    description: '根据细纲和上下文写出章节正文。',
    category: '正文编写',
    params: [
      { key: 'novelTitle', label: '小说标题' },
      { key: 'chapterNum', label: '章节编号' },
      { key: 'chapterTitle', label: '章节标题' },
      { key: 'chapterGoal', label: '本章目标' },
      { key: 'plotPoints', label: '章节大纲' },
      { key: 'emotionTone', label: '情绪基调' },
      { key: 'targetWords', label: '目标字数' },
      { key: 'storyCore', label: '故事核心' },
      { key: 'currentArc', label: '当前故事弧' },
      { key: 'worldRules', label: '世界规则' },
      { key: 'characterStates', label: '人物状态' },
      { key: 'previousSummaries', label: '近章摘要' },
      { key: 'previousChapterContext', label: '上一章关键先验' },
      { key: 'lastChapterEnding', label: '上章结尾' },
      { key: 'chapterBridgePlan', label: '章节衔接桥' },
      { key: 'stepMemorySummary', label: '步骤接力记忆' },
      { key: 'runtimeAssertions', label: '运行时接力断言' },
      { key: 'styleTemplate', label: '文风参考' },
      { key: 'continuitySummary', label: '连续性记忆' },
      { key: 'recalledMemory', label: '向量召回记忆' },
      { key: 'openLoops', label: '未回收事项' },
      { key: 'continuityNotes', label: '必须承接事项' },
      { key: 'timelineSummary', label: '时间轴关键节点' },
      { key: 'timelineOpenThreads', label: '时间轴待回收事项' },
      { key: 'protagonistReference', label: '主角称呼' },
      { key: 'protagonistRule', label: '主角命名规则' },
    ],
    template: buildChapterWritingPrompt({
      novelTitle: placeholder('novelTitle'),
      chapterNum: Number.NaN,
      chapterTitle: placeholder('chapterTitle'),
      chapterGoal: placeholder('chapterGoal'),
      plotPoints: placeholder('plotPoints'),
      emotionTone: placeholder('emotionTone'),
      targetWords: Number.NaN,
      storyCore: placeholder('storyCore'),
      currentArc: placeholder('currentArc'),
      worldRules: placeholder('worldRules'),
      characterStates: placeholder('characterStates'),
      previousSummaries: placeholder('previousSummaries'),
      previousChapterContext: placeholder('previousChapterContext'),
      lastChapterEnding: placeholder('lastChapterEnding'),
      chapterBridgePlan: placeholder('chapterBridgePlan'),
      stepMemorySummary: placeholder('stepMemorySummary'),
      runtimeAssertions: [placeholder('runtimeAssertions')],
      styleTemplate: placeholder('styleTemplate'),
      continuitySummary: placeholder('continuitySummary'),
      recalledMemory: placeholder('recalledMemory'),
      openLoops: placeholder('openLoops'),
      continuityNotes: placeholder('continuityNotes'),
      timelineSummary: placeholder('timelineSummary'),
      timelineOpenThreads: placeholder('timelineOpenThreads'),
      protagonistReference: placeholder('protagonistReference'),
      protagonistRule: placeholder('protagonistRule'),
    }).replace('NaN', placeholder('chapterNum')).replace('NaN', placeholder('targetWords')),
  },
  {
    key: 'chapterSummary',
    name: '章节摘要生成',
    description: '为完成章节生成后续写作摘要。',
    category: '正文编写',
    params: [{ key: 'chapterContent', label: '章节内容' }],
    template: chapterSummaryPrompt(placeholder('chapterContent')),
  },
  {
    key: 'continuityState',
    name: '连续性记忆提炼',
    description: '从当前章节提炼后文必须记住的事实。',
    category: '正文编写',
    params: [
      { key: 'novelTitle', label: '小说标题' },
      { key: 'chapterNum', label: '章节编号' },
      { key: 'chapterTitle', label: '章节标题' },
      { key: 'arcName', label: '故事弧名称' },
      { key: 'chapterGoal', label: '本章目标' },
      { key: 'summary', label: '本章摘要' },
      { key: 'chapterContent', label: '章节正文' },
    ],
    template: buildContinuityStatePrompt({
      novelTitle: placeholder('novelTitle'),
      chapterNum: Number.NaN,
      chapterTitle: placeholder('chapterTitle'),
      arcName: placeholder('arcName'),
      chapterGoal: placeholder('chapterGoal'),
      summary: placeholder('summary'),
      chapterContent: placeholder('chapterContent'),
    }).replace('NaN', placeholder('chapterNum')),
  },
  {
    key: 'aiCheck',
    name: 'AI 检测·AI 痕迹',
    description: '检测文本里的模板腔和 AI 写作痕迹。',
    category: '正文编写',
    params: [{ key: 'text', label: '待检测文本' }],
    template: aiCheckPrompt(placeholder('text')),
  },
  {
    key: 'rewriteParagraph',
    name: '段落重写',
    description: '保留情节信息，压低模板腔和 AI 痕迹。',
    category: '正文编写',
    params: [
      { key: 'originalParagraph', label: '原段落' },
      { key: 'contextBefore', label: '前文上下文' },
      { key: 'specificRequirements', label: '额外要求' },
    ],
    template: rewriteParagraphPrompt({
      originalParagraph: placeholder('originalParagraph'),
      contextBefore: placeholder('contextBefore'),
      specificRequirements: placeholder('specificRequirements'),
    }),
  },
  {
    key: 'contentScoring',
    name: '内容评分',
    description: '从编辑和读者两侧评估内容质量与 AI 痕迹。',
    category: '正文编写',
    params: [
      { key: 'contentType', label: '内容类型' },
      { key: 'content', label: '待评估内容' },
      { key: 'genreContext', label: '题材' },
      { key: 'novelBackground', label: '故事背景' },
    ],
    template: contentScoringPrompt({
      contentType: placeholder('contentType'),
      content: placeholder('content'),
      genreContext: placeholder('genreContext'),
      novelBackground: placeholder('novelBackground'),
    }),
  },
  {
    key: 'mapGeneration',
    name: '地图生成',
    description: '生成能承载剧情的三层地图结构。',
    category: '世界构建',
    params: [
      { key: 'novelTitle', label: '小说标题' },
      { key: 'worldSummary', label: '世界观摘要' },
      { key: 'genre', label: '题材' },
      { key: 'mapStructure', label: '地图结构' },
      { key: 'namedPlaces', label: '已命名地点' },
    ],
    template: mapGenerationPrompt({
      novelTitle: placeholder('novelTitle'),
      worldSummary: placeholder('worldSummary'),
      genre: placeholder('genre'),
      mapStructure: placeholder('mapStructure'),
      namedPlaces: placeholder('namedPlaces'),
    }),
  },
]
