import type {
  ChapterRewritePromptInput,
  ChapterWritingPromptInput,
  RewriteParagraphPromptInput,
} from './prompt-types'
import {
  GLOBAL_WRITING_RULES,
  buildAvoidanceSection,
  buildGenreCoreExecutionGuidance,
  buildGoldenThreeChapterGuidance,
  buildHumanLanguageRules,
  buildPromptGuardrailSections,
  buildRuntimeAssertionSection,
  buildStepMemoryContinuityGuidance,
  buildVariationHint,
  formatTargetWordsBand,
  renderPrompt,
  section,
  sectionLines,
  sectionUnlessCovered,
} from './prompt-common'

export { GLOBAL_WRITING_RULES }

export function buildChapterWritingPrompt(params: ChapterWritingPromptInput): string {
  return renderPrompt([
    GLOBAL_WRITING_RULES,
    '下面是这一章的任务卡。先吃透任务，再直接写正文。',
    sectionLines('章节信息', [
      '小说：' + params.novelTitle,
      '章节：第' + params.chapterNum + '章 ' + params.chapterTitle,
      '主角称呼：' + params.protagonistReference,
      '主角命名规则：' + params.protagonistRule,
      formatTargetWordsBand(params.targetWords),
      params.emotionTone ? '情绪基调：' + params.emotionTone : '',
    ]),
    ...buildPromptGuardrailSections({
      genre: params.genre,
      storyCore: params.storyCore,
      worldSummary: params.worldRules,
      taskFocus: '先把事件链、动作链和后果链写顺，再让情绪自然浮出来。',
      extraContextLines: ['每个场景要么推进本章任务，要么承担关系、伏笔、质感或喘息的次级功能；允许有节制的闲笔和日常，但每一段都要有存在理由，不写无信息增量的注水段落。'],
      extraRealityLines: ['遇到不准确搭配，优先改成读者最熟悉、最准确的常规说法。'],
    }),
    sectionUnlessCovered('本章必须完成', params.chapterGoal || '按已定大纲执行', params.hardConstraintContext, ['本章目标', '章节目标']),
    section('硬约束', params.hardConstraintContext),
    section('角色 Voice Lock', params.dialogueVoiceLocks),
    section('已定章节大纲', params.plotPoints),
    sectionUnlessCovered('写作类型', params.writingContractSummary, params.hardConstraintContext, ['写作合同/章节合同']),
    section('章节级主题验证', params.themeChapterTest),
    sectionUnlessCovered('关键人物关系', params.relationSummary, params.hardConstraintContext),
    sectionUnlessCovered('本章必须承接', params.continuityNotes, params.hardConstraintContext, ['必须承接']),
    sectionUnlessCovered('当前未回收事项', params.openLoops, params.hardConstraintContext, ['未回收事项', '必须回收事项']),
    section('本章应回收伏笔', params.dueForeshadows),
    section('时间轴关键节点', params.timelineSummary),
    section('时间轴待回收事项', params.timelineOpenThreads),
    section('活跃支线与伏笔', params.activeThreads),
    section('POV 约束', params.povGuidance),
    section('POV 轮转建议', params.povRotationGuidance),
    section('感官雷达', params.sensoryGuidance),
    section('叙事比例', params.narrativeRatioGuidance),
    section('章节衔接桥', params.chapterBridgePlan),
    section('步骤接力记忆', params.stepMemorySummary),
    buildRuntimeAssertionSection(params.runtimeAssertions),
    buildGoldenThreeChapterGuidance(params.chapterNum, 'writing'),
    buildStepMemoryContinuityGuidance('writing'),
    buildGenreCoreExecutionGuidance({
      genre: params.genre,
      novelTitle: params.novelTitle,
      storyCore: params.storyCore,
      stage: 'writing',
    }),
    section('节奏曲线', params.storyPacingGuidance),
    section('钩子连续性', params.hookContinuityGuidance),
    section('上一章关键先验', params.previousChapterContext),
    section('上章结尾', params.lastChapterEnding),
    sectionUnlessCovered('当前人物状态', params.characterStates, params.hardConstraintContext, ['人物当前状态']),
    sectionUnlessCovered('当前世界状态', params.worldStates, params.hardConstraintContext),
    section('地图地点上下文', params.mapSummary),
    sectionUnlessCovered('关键物品与去向', params.itemSummary, params.hardConstraintContext, ['关键物品去向']),
    section('当前故事弧', params.currentArc),
    section('小说核心约束', params.storyCore),
    section('世界规则与限制', params.worldRules),
    section('近章摘要', params.previousSummaries),
    section('连续性记忆', params.continuitySummary),
    section('向量召回记忆', params.recalledMemory),
    section('跨章表达去重', params.expressionDedupGuidance),
    section('摘要健康', params.summaryHealthGuidance),
    section('角色声音进化', params.voiceEvolutionGuidance),
    section('文风参考', params.styleTemplate),
    section('场景写作材料', params.sceneWritingBrief),
    section('写作要求', [
      '先把事件链、动作链和后果链写顺，再让情绪自然浮出来。',
      '人物说话要像这个人当下会说的话，别让所有角色一个语气。',
      '能直接写事实时，不要用“不是……而是……”做解释性对照；对白语气不要靠“声音很轻/很低/压得很低”标签交代。',
      '如果上下文给了关系摘要，就把亲疏、权力差、潜台词和说话习惯写进对白。',
      '主角在本章里可以害怕、迟疑、失望、心软或犯错，但这些反应必须推动后续选择。',
      '如果提供了章节级主题验证，至少让一个具体场景逼出角色对命题的可见判断，并写清选择付出的即时代价与留下的关系、制度、资源或身份后果；不要用旁白总结代替事件。',
      '每个场景要么推进本章任务，要么承担关系、伏笔、质感或喘息的次级功能；允许有节制的闲笔与日常，但不写无信息增量的注水段落。',
      '每完成一个场景或一段自然叙事单元，都要出现可感知的变化：军令、账册、物资、关系、态度、位置、伤亡、线索或选择至少有一项发生改变；不要用固定字数切段。',
      '段落节奏要参差：不要每段都三五句、不要每段都用动作或总结收尾；允许被打断的句子、答非所问、未说完的命令和留白。',
      '涉及历史/战争/权谋时，至少把一个抽象压力落到具体材料上：官职程序、传报时差、粮草数目、船型地形、伤亡清点、军纪执行或奏疏措辞。',
      '不要让旁白替人物把道理说完；把判断拆回人物当场能看到的证据、愿意付出的代价和不敢说出口的顾虑。',
      '如果给了文风参考，只借叙述气质、视角和句子密度，不模仿具体作者。',
      '遇到不准确搭配，优先改成读者最熟悉、最准确的常规说法。',
      '新增地点、房间、楼梯、方位、设备构造、数字和背景细节，必须能在硬约束、世界规则、章节合同、场景计划、既有正文或可观察物件中找到来源；没有来源时用已知地点泛称，不得把模型补出的细节写成事实。',
      '只输出正文，不要解释。正文第一行直接进入叙事，不要写“第X章”、章节标题或任何标题行。',
    ].join('\n')),
    buildAvoidanceSection(params.rejectedDigests || []),
    params.attemptNumber && params.attemptNumber > 1 ? buildVariationHint(params.attemptNumber, 'chapter') : '',
  ])
}

export function buildChapterDraftPrompt(params: ChapterRewritePromptInput): string {
  return renderPrompt([
    GLOBAL_WRITING_RULES,
    '先根据场景计划写出一版完整初稿。重点是把事情写顺、把承接写准，先不要追求花哨修辞。',
    sectionLines('章节信息', [
      '小说：' + params.novelTitle,
      '章节：第' + params.chapterNum + '章 ' + params.chapterTitle,
      '主角称呼：' + params.protagonistReference,
      '主角命名规则：' + params.protagonistRule,
      formatTargetWordsBand(params.targetWords),
      params.emotionTone ? '情绪基调：' + params.emotionTone : '',
    ]),
    ...buildPromptGuardrailSections({
      genre: params.genre,
      storyCore: params.storyCore,
      worldSummary: params.worldRules,
      taskFocus: '只按场景计划推进，不跳场景，不漏 必须交代项。',
      extraContextLines: ['只按场景计划推进，不跳场景，不漏 必须交代项。'],
      extraRealityLines: ['人物状态、物品去向、地点变换和事件顺序必须写准，避免后面大修。'],
    }),
    section('场景计划', params.scenePlan),
    section('场景写作材料', params.sceneWritingBrief),
    sectionUnlessCovered('本章目标', params.chapterGoal, params.hardConstraintContext, ['章节目标']),
    section('硬约束', params.hardConstraintContext),
    section('角色 Voice Lock', params.dialogueVoiceLocks),
    section('当前故事弧', params.currentArc),
    section('小说核心约束', params.storyCore),
    sectionUnlessCovered('写作类型', params.writingContractSummary, params.hardConstraintContext, ['写作合同/章节合同']),
    section('章节级主题验证', params.themeChapterTest),
    sectionUnlessCovered('关键人物关系', params.relationSummary, params.hardConstraintContext),
    section('世界规则', params.worldRules),
    sectionUnlessCovered('人物当前状态', params.characterStates, params.hardConstraintContext),
    sectionUnlessCovered('当前世界状态', params.worldStates, params.hardConstraintContext),
    section('地图地点上下文', params.mapSummary),
    sectionUnlessCovered('关键物品与去向', params.itemSummary, params.hardConstraintContext, ['关键物品去向']),
    section('上一章关键先验', params.previousChapterContext),
    section('上章结尾', params.lastChapterEnding),
    section('章节衔接桥', params.chapterBridgePlan),
    section('步骤接力记忆', params.stepMemorySummary),
    buildRuntimeAssertionSection(params.runtimeAssertions),
    buildGoldenThreeChapterGuidance(params.chapterNum, 'draft'),
    buildStepMemoryContinuityGuidance('draft'),
    buildGenreCoreExecutionGuidance({
      genre: params.genre,
      novelTitle: params.novelTitle,
      storyCore: params.storyCore,
      stage: 'draft',
    }),
    section('最近章节摘要', params.previousSummaries),
    section('连续性记忆', params.continuitySummary),
    sectionUnlessCovered('必须承接', params.continuityNotes, params.hardConstraintContext),
    sectionUnlessCovered('未回收事项', params.openLoops, params.hardConstraintContext, ['必须回收事项']),
    section('本章应回收伏笔', params.dueForeshadows),
    section('时间轴锚点', params.timelineSummary),
    section('时间轴待回收', params.timelineOpenThreads),
    section('活跃支线与伏笔', params.activeThreads),
    section('POV 约束', params.povGuidance),
    section('POV 轮转建议', params.povRotationGuidance),
    section('感官雷达', params.sensoryGuidance),
    section('叙事比例', params.narrativeRatioGuidance),
    section('节奏曲线', params.storyPacingGuidance),
    section('钩子连续性', params.hookContinuityGuidance),
    section('长文压缩记忆', params.longTermMemory),
    section('向量召回记忆', params.recalledMemory),
    section('跨章表达去重', params.expressionDedupGuidance),
    section('摘要健康', params.summaryHealthGuidance),
    section('角色声音进化', params.voiceEvolutionGuidance),
    section('结构体检提醒', params.consistencyNotes),
    section('近期结构告警', params.structuralAlertsSummary),
    section('初稿要求', [
      '只按场景计划推进，不跳场景，不漏 must_cover。',
      '先把行为、对话、信息交接和后果写清，再处理气氛。',
      '每个主要场景都要包含可观察动作、可感知环境细节、人物选择和场景结束后的状态变化，不能只写心理总结。',
      '人物情绪必须通过停顿、动作、措辞变化、错误判断、资源消耗或关系反应体现，禁止用“他心中一震”“命运的齿轮”“某种情绪蔓延”这类模板句替代刻画。',
      '冲突不能只靠外部口号推进：至少写出一处具体阻力、一处主角判断成本、一处后续仍会持续的代价或未解决问题。',
      '如果提供了章节级主题验证，初稿必须把主题问题、角色选择、即时代价和后果落进至少一个场景；正文中要能找到动作、对白或结果证据。',
      '初稿允许有人的不整齐：场景中可以有犹豫、误读、答非所问、账目没对上、传令迟到、官文措辞被改，不要把所有信息处理得过度干净。',
      '每个场景或关键叙事单元至少推进一个可追踪变量：人物立场、资源余量、伤亡压力、地理位置、支线状态、伏笔状态或下一章压力；不要用固定字数切段。',
      '同一类感官意象一章最多保留两组，多余篇幅改写成行为、制度、物资、路线或对白博弈。',
      '涉及多人对话时，家人、朋友、陌生人、上下级和恋爱关系不能一个语气。',
      '对白每轮必须承担信息推进、关系变化、试探遮掩或行动决策之一；删掉寒暄式互相解释和角色替作者讲设定的句子。',
      '让成长落在事件、关系和代价里，不要只在段尾用一句总结硬说人物成长。',
      '人物状态、物品去向、地点变换和事件顺序必须写准，避免后面大修。',
      '如果某段只有情绪没有动作或结果，补上能落地的外部承载。',
      '如果近期结构告警提示主角太顺、代价蒸发、反转硬塞或高潮分布异常，必须在本章补出真实阻力、持续后果、铺垫兑现或节奏缓冲。',
      '叙事视角一致性：全篇保持同一叙事人称和视角限制。如果是第三人称限制视角，只能写视角角色能看到、听到、感受到的内容，不能偷跑到其他角色的内心。如果是第一人称，不能突然出现"他想着"这种第三人称描写。',
      '章节开头过渡：本章前 200 字必须自然衔接上章结尾的情境（时间、地点、情绪、未完成的动作），不能跳过不交代就进入新场景。',
      '只输出初稿正文，不要解释。正文第一行直接进入叙事，不要写“第X章”、章节标题或任何标题行。',
    ].join('\n')),
    buildAvoidanceSection(params.rejectedDigests || []),
    params.attemptNumber && params.attemptNumber > 1 ? buildVariationHint(params.attemptNumber, 'chapter') : '',
  ])
}

export function buildChapterRewritePrompt(params: ChapterRewritePromptInput): string {
  return renderPrompt([
    GLOBAL_WRITING_RULES,
    '把这一章重写成可直接入稿的版本。先修连续性、因果、人物状态、真实度、时间和物品准确性，最后再打磨语言。',
    sectionLines('章节信息', [
      '小说：' + params.novelTitle,
      '章节：第' + params.chapterNum + '章 ' + params.chapterTitle,
      '主角称呼：' + params.protagonistReference,
      '主角命名规则：' + params.protagonistRule,
      formatTargetWordsBand(params.targetWords),
      params.emotionTone ? '情绪基调：' + params.emotionTone : '',
    ]),
    ...buildPromptGuardrailSections({
      genre: params.genre,
      storyCore: params.storyCore,
      worldSummary: params.worldRules,
      taskFocus: '只在既有上下文内重写，同时修复连续性、真实度和语言风险。',
      extraContextLines: ['不要通过删掉剧情压力或改写章节目标来假装解决上下文问题。'],
      extraRealityLines: ['如果审校指出反应、伤势、代价、移动跳跃或能力使用不合理，必须在正文里明确修正。'],
    }),
    section('场景计划', params.scenePlan),
    section('场景计划摘要', params.scenePlanSummary),
    section('当前稿件', params.draftContent),
    section('当前稿件摘要', params.draftTextSummary),
    section('作者锁定段落（逐字保留）', params.lockedParagraphs?.join('\n\n')),
    section('审校意见', params.reviewNotes),
    section('审校风险摘要', params.reviewRiskSummary),
    section('审校证据摘要', params.reviewProofSummary),
    section('重写差量摘要', params.rewriteDeltaSummary),
    section('合同版本摘要', params.contractVersionSummary),
    section('发布门风险', params.publishGateRiskSummary),
    sectionUnlessCovered('本章目标', params.chapterGoal, params.hardConstraintContext, ['章节目标']),
    section('硬约束', params.hardConstraintContext),
    section('角色 Voice Lock', params.dialogueVoiceLocks),
    section('当前故事弧', params.currentArc),
    section('小说核心', params.storyCore),
    sectionUnlessCovered('写作类型', params.writingContractSummary, params.hardConstraintContext, ['写作合同/章节合同']),
    section('章节级主题验证', params.themeChapterTest),
    sectionUnlessCovered('关键人物关系', params.relationSummary, params.hardConstraintContext),
    section('世界规则', params.worldRules),
    sectionUnlessCovered('人物当前状态', params.characterStates, params.hardConstraintContext),
    sectionUnlessCovered('当前世界状态', params.worldStates, params.hardConstraintContext),
    section('地图地点上下文', params.mapSummary),
    sectionUnlessCovered('关键物品与去向', params.itemSummary, params.hardConstraintContext, ['关键物品去向']),
    section('上一章关键先验', params.previousChapterContext),
    section('上章结尾', params.lastChapterEnding),
    section('章节衔接桥', params.chapterBridgePlan),
    section('步骤接力记忆', params.stepMemorySummary),
    buildRuntimeAssertionSection(params.runtimeAssertions),
    buildGoldenThreeChapterGuidance(params.chapterNum, 'rewrite'),
    buildStepMemoryContinuityGuidance('rewrite'),
    buildGenreCoreExecutionGuidance({
      genre: params.genre,
      novelTitle: params.novelTitle,
      storyCore: params.storyCore,
      stage: 'rewrite',
    }),
    section('近章摘要', params.previousSummaries),
    section('连续性记忆', params.continuitySummary),
    sectionUnlessCovered('必须承接', params.continuityNotes, params.hardConstraintContext),
    sectionUnlessCovered('未回收事项', params.openLoops, params.hardConstraintContext, ['必须回收事项']),
    section('本章应回收伏笔', params.dueForeshadows),
    section('时间轴锚点', params.timelineSummary),
    section('时间轴待回收', params.timelineOpenThreads),
    section('长期记忆', params.longTermMemory),
    section('向量召回记忆', params.recalledMemory),
    section('POV 约束', params.povGuidance),
    section('POV 轮转建议', params.povRotationGuidance),
    section('感官雷达', params.sensoryGuidance),
    section('叙事比例', params.narrativeRatioGuidance),
    section('节奏曲线', params.storyPacingGuidance),
    section('钩子连续性', params.hookContinuityGuidance),
    section('跨章表达去重', params.expressionDedupGuidance),
    section('摘要健康', params.summaryHealthGuidance),
    section('角色声音进化', params.voiceEvolutionGuidance),
    section('结构体检提醒', params.consistencyNotes),
    section('近期结构告警', params.structuralAlertsSummary),
    section('重写要求', [
      '已经成立的段落可以保留，但凡是影响成稿质量的都要修。',
      '如果场景计划里的 must_cover 漏了，补上。',
      '先修因果、指代清晰度、节奏、人物反应和真实度，最后再抛光语言。',
      '删掉空洞抒情、模板句和解释性旁白，把情绪放回动作、对话和细节里。',
      '把每个主要场景改成“具体阻力 -> 人物判断 -> 行动代价 -> 状态变化”的链条，不能只保留气氛、震惊和旁白解释。',
      '补足人物的私心、误判、顾虑、迟疑或遮掩，让角色像在维护自己的利益和关系，而不是替作者朗读剧情。',
      '对话重写时优先压缩说明句，改成试探、反问、打断、避重就轻、交换条件或暴露关系温度的说法。',
      '重写时主动破除过度工整的 AI 节奏：合并部分碎句，拆开过长说明段，保留少量现实中的停顿和信息误差。',
      '如果审校命中高频重复称谓/姓名，优先在不造成歧义的前提下改用动作主语、代词、职业/关系称呼或省略主语；同一姓名不要在相邻句中机械重复。',
      '如果审校命中破折号滥用，删除解释型和假停顿型破折号，把补充信息改成动作、事实或独立短句；只有真实打断、抢话或语气断裂才保留。',
      '如果原稿气氛意象密集，保留最有行动价值的 1 到 2 处，其余改成账册、路线、官职程序、物件去向、人物站位或下一步命令。',
      '如果原稿每段都用结论收束，把至少三处结尾改成未完成动作、具体数字、未答复问题或继续存在的代价。',
      '把关系温度、权力差和潜台词写回称呼、打断、停顿和回避方式，不要让所有对白一个基调。',
      '把成长变化写回事件、关系、资源和代价，不要只靠总结句宣告人物成长。',
      '如果提供了章节级主题验证，必须补齐主题问题、角色选择、即时代价和后果四个证据环节；主题缺口属于结构修复，不得只润色措辞。',
      '在同一轮里一起修好上下文漂移、常识失效、规则越界、零代价奇迹和 AI 腔。',
      '删除或泛化无来源的地点、房间、楼梯、方位、设备构造、数字和背景细节；只有能从硬约束、章节合同、场景计划、既有正文或可观察物件追溯的细节才能保留为事实。',
      '如果近期结构告警提示主角太顺，就补出真实受挫、失误或代价；如果提示代价蒸发，就把后果延续到本章；如果提示反转硬塞，就补足前文呼应和触发链；如果提示高潮过密或过疏，就主动收束或蓄力。',
      '叙事视角一致性：检查并修正任何视角跳跃——限制视角不能写不在场角色的心理活动，第一人称不能突然变第三人称。如果初稿中有视角滑移，重写时修正为一致的视角。',
      '章节过渡：确保开头自然衔接上章结尾（参考"上章结尾"段），时间/地点/情绪过渡平滑，不能跳过未交代就进入新场景。',
      '作者锁定段落不得改写、删减、拆分、合并或替换措辞，只能改动周边段落来完成衔接。',
      '如果审校意见里有字数带宽或压缩要求，删减时优先砍微动作细节堆叠和重复描写，保留全部事件、冲突结果与伏笔。',
      '只输出重写后的最终正文。正文第一行直接进入叙事，不要写“第X章”、章节标题或任何标题行。',
    ].join('\n')),
    buildAvoidanceSection(params.rejectedDigests || []),
    params.attemptNumber && params.attemptNumber > 1 ? buildVariationHint(params.attemptNumber, 'chapter') : '',
  ])
}

export function chapterWritingPrompt(params: {
  novelTitle: string
  chapterNum: number
  chapterTitle: string
  chapterGoal: string
  hardConstraintContext?: string
  dialogueVoiceLocks?: string
  plotPoints: string
  emotionTone: string
  worldRules: string
  characterStates: string
  worldStates?: string
  previousSummaries: string
  previousChapterContext: string
  lastChapterEnding: string
  styleTemplate: string
  targetWords: number
  genre?: string
  storyCore?: string
  currentArc?: string
  themeChapterTest?: string
  continuitySummary?: string
  openLoops?: string
  continuityNotes?: string
  timelineSummary?: string
  timelineOpenThreads?: string
  recalledMemory?: string
  protagonistReference?: string
  protagonistRule?: string
}): string {
  return buildChapterWritingPrompt({
    novelTitle: params.novelTitle,
    chapterNum: params.chapterNum,
    chapterTitle: params.chapterTitle,
    chapterGoal: params.chapterGoal,
    hardConstraintContext: params.hardConstraintContext || '',
    dialogueVoiceLocks: params.dialogueVoiceLocks || '',
    plotPoints: params.plotPoints,
    emotionTone: params.emotionTone,
    targetWords: params.targetWords,
    genre: params.genre || '',
    storyCore: params.storyCore || '',
    currentArc: params.currentArc || '',
    themeChapterTest: params.themeChapterTest || '',
    worldRules: params.worldRules,
    characterStates: params.characterStates,
    worldStates: params.worldStates || '',
    previousSummaries: params.previousSummaries,
    previousChapterContext: params.previousChapterContext,
    lastChapterEnding: params.lastChapterEnding,
    styleTemplate: params.styleTemplate,
    continuitySummary: params.continuitySummary || '',
    openLoops: params.openLoops || '',
    continuityNotes: params.continuityNotes || '',
    timelineSummary: params.timelineSummary || '',
    timelineOpenThreads: params.timelineOpenThreads || '',
    recalledMemory: params.recalledMemory || '',
    protagonistReference: params.protagonistReference || '主角',
    protagonistRule: params.protagonistRule || '若涉及主角，沿用现有设定中的唯一称呼，不要擅自改名。',
  })
}

export function rewriteParagraphPrompt(params: RewriteParagraphPromptInput): string {
  return renderPrompt([
    GLOBAL_WRITING_RULES,
    '把下面这段文字改得更像人写的，但不要改动核心事件和信息。',
    section('原段落', params.originalParagraph),
    section('前文参考', params.contextBefore),
    section('额外要求', params.specificRequirements || '保持原意，让语言更自然、更贴人。'),
    ...buildPromptGuardrailSections({
      genre: params.genreContext,
      background: params.contextBefore,
      worldSummary: params.worldSummary,
      taskFocus: '先保住情节和信息，再处理语气、句式和细节。',
      extraQualityLines: ['逐句检查搭配是否成立，把不符合常规汉语的表达改成准确说法。'],
    }),
    section('改写原则', [
      '先保住情节和信息，再处理语气、句式和细节。',
      '少解释，多把心理落到动作、反应、对话里。',
      '拆掉明显模板句、万能词和假深刻表达。',
      '逐句检查搭配是否成立，把不符合常规汉语的表达改成准确说法。',
      '只输出改写后的纯文本，不要解释。',
    ].join('\n')),
    section('语言修复重点', buildHumanLanguageRules([
      '不要保留“物体死亡”“系统悲鸣”这类高歧义或不成立表达。',
    ])),
  ])
}
