const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { app, BrowserWindow } = require('electron')
const { buildSync } = require('esbuild')
const root = path.resolve(__dirname, '..')
fs.mkdirSync(path.join(root, '.tmp-tests'), { recursive: true })
const temp = fs.mkdtempSync(path.join(root, '.tmp-tests', 'chapter-index-ui-'))
app.setPath('userData', temp)
app.disableHardwareAcceleration()
const data = (novelId, keyword = 1, pending = 1) => ({ novelId, savedChapterCount: 2, keywordIndexedChapterCount: keyword, vectorIndexedChapterCount: keyword, queue: { pending, processing: 0, failed: 0, dead_letter: 0 }, errors: [] })

async function main() {
  await app.whenReady()
  const bundle = path.join(temp, 'fixture.js')
  buildSync({ stdin: { contents: `import React from 'react'; import {createRoot} from 'react-dom/client'; import ChapterIndexStatus from './src/pages/Novel/AuthorWorkspace/ChapterIndexStatus';
    const calls=[]; window.calls=calls; window.electron={agentTools:{call:request=>new Promise(resolve=>calls.push({request,resolve}))}};
    const root=createRoot(document.getElementById('root')); window.renderNovel=id=>root.render(<ChapterIndexStatus novelId={id}/>); window.renderNovel(1);`, resolveDir: root, loader: 'tsx' }, bundle: true, outfile: bundle, platform: 'browser' })
  fs.writeFileSync(path.join(temp, 'index.html'), '<div id="root"></div><script src="fixture.js"></script>')
  const browser = new BrowserWindow({ show: false, webPreferences: { contextIsolation: false, nodeIntegration: false, backgroundThrottling: false } })
  await browser.loadFile(path.join(temp, 'index.html'))
  const run = source => browser.webContents.executeJavaScript(source)
  const wait = async source => {
    for (let i = 0; i < 100; i++) {
      if (await run(source)) return
      await new Promise(resolve => setTimeout(resolve, 10))
    }
    throw new Error(`UI fixture condition timed out: ${source}`)
  }
  const resolve = (index, status) => run(`window.calls[${index}].resolve({ok:true,data:${JSON.stringify(status)}})`)
  await wait('window.calls.length === 1')
  await resolve(0, data(1))
  await wait("document.querySelector('summary').textContent.includes('1/2')")
  await run("document.querySelector('summary').click()")
  await wait('window.calls.length === 2 && document.querySelectorAll("button").length === 2')
  assert.equal(await run('document.querySelectorAll("button")[0].disabled'), false, 'text repair remains available while vector work is queued')
  await run('document.querySelectorAll("button")[0].click(); document.querySelectorAll("button")[0].click()')
  await wait('window.calls.length === 3')
  assert.equal(await run('window.calls.filter(item=>item.request.toolId.endsWith("index_rebuild")).length'), 1, 'double click produces one mutation')
  await run("document.querySelector('summary').click()")
  await wait("!document.querySelector('details').open")
  await run("document.querySelector('summary').click()")
  await wait('document.querySelectorAll("button").length === 2')
  assert.equal(await run('document.querySelectorAll("button")[0].disabled'), true, 'close/reopen does not release the mutation lock')
  await resolve(2, data(1, 2, 0))
  await wait("document.querySelector('summary').textContent.includes('2/2')")
  await resolve(1, data(1, 0, 0))
  await wait('window.calls.length === 4')
  assert.ok((await run('document.querySelector("summary").textContent')).includes('2/2'), 'older read cannot replace rebuilt status')
  await resolve(3, data(1, 2, 0))
  await wait('!document.querySelectorAll("button")[0].disabled')

  await run('document.querySelectorAll("button")[1].click()')
  await wait('window.calls.length === 5')
  await run('window.renderNovel(2)')
  await wait('window.calls.length === 6')
  await resolve(5, data(2, 1, 1))
  await resolve(4, data(1, 2, 0))
  await wait("document.querySelector('summary').textContent.includes('1/2')")
  assert.ok(!(await run('document.querySelector("summary").textContent')).includes('2/2'), 'previous project response cannot update new project')
  await run("window.dispatchEvent(new Event('novelforge:creative-completed')); window.dispatchEvent(new Event('novelforge:creative-completed'))")
  await wait('window.calls.length === 7')
  await resolve(6, data(2, 1, 1))
  await wait('window.calls.length === 8')
  await resolve(7, data(2, 1, 1))
  await wait("document.querySelector('summary').textContent.includes('1/2')")
  // Repeated refresh signals coalesce into one pending read and one timer.
  await new Promise(resolve => setTimeout(resolve, 5200))
  assert.equal(await run('window.calls.length'), 9)
  await resolve(8, data(2, 2, 0))
  await run('window.renderNovel(3)')
  await wait('window.calls.length === 10')
  await run("window.calls[9].resolve({ok:false,error:{code:'TOOL_NOT_FOUND',message:'old runtime'}})")
  await wait("document.querySelector('summary').textContent.includes('更新后可用')")
  await run("window.dispatchEvent(new Event('novelforge:creative-completed'))")
  assert.equal(await run('window.calls.length'), 10, 'unsupported runtime does not repeatedly request missing tools')
  browser.destroy()
  console.log('[chapter-index-ui] React DOM toggle/mutation, stale reads, project switch, text repair, coalesced polls and old runtime passed')
}
main().then(() => app.exit(0)).catch(error => { console.error(error); app.exit(1) })
