const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { app } = require('electron')
const { registerProjectTsRuntime } = require('./register-project-ts.cjs')
const root = path.resolve(__dirname, '..')
fs.mkdirSync(path.join(root, '.tmp-tests'), { recursive: true })
const temp = fs.mkdtempSync(path.join(root, '.tmp-tests', 'chapter-index-'))
app.setPath('userData', temp)
app.disableHardwareAcceleration()
process.env.NOVELFORGE_DISABLE_LEGACY_DB_COPY = '1'
registerProjectTsRuntime(root)

async function main() {
  await app.whenReady()
  const { initDb, closeDb, getSqlite } = require('../electron/database/db.ts')
  initDb()
  const sqlite = getSqlite()
  const model = require('../electron/services/model.service.ts')
  const embedding = require('../electron/services/embedding.service.ts')
  const { rebuildChapterIndex, getChapterIndexStatus } = require('../electron/services/chapter-index.service.ts')
  const { processSemanticMemoryOutbox } = require('../electron/services/semantic-memory.service.ts')
  const { AgentToolRegistry } = require('../electron/application/tool-registry.ts')
  const { registerChapterIndexTools } = require('../electron/application/chapter-index-tools.ts')
  const { DESKTOP_AGENT_TOOL_SCOPES } = require('../src/shared/tool-contracts/index.ts')
  const modelId = Number(sqlite.prepare('INSERT INTO model_configs(name,provider,model_id,api_key,is_default) VALUES(?,?,?,?,1)').run('Index fixture', 'openai', 'fixture', model.encryptApiKey('fixture-only')).lastInsertRowid)
  const settings = require('../electron/services/embedding-settings.service.ts')
  settings.setEmbeddingSettings({ mode: 'remote', modelConfigId: modelId, modelId: 'fixture-vector' })
  const novelId = Number(sqlite.prepare('INSERT INTO novels(title,model_config_id) VALUES(?,?)').run('索引试验', modelId).lastInsertRowid)
  const otherNovelId = Number(sqlite.prepare('INSERT INTO novels(title) VALUES(?)').run('其他项目').lastInsertRowid)
  const original = `${'第一段。'.repeat(450)}\n\n铜牌在中段箱底。\n\n${'结尾。'.repeat(450)}`
  const chapterId = Number(sqlite.prepare('INSERT INTO chapters(novel_id,chapter_num,content,outline) VALUES(?,?,?,?)').run(novelId, 1, original, '未来铜牌要被毁').lastInsertRowid)
  const futureId = Number(sqlite.prepare('INSERT INTO chapters(novel_id,chapter_num,outline) VALUES(?,?,?)').run(novelId, 2, '未来密谋尚未发生').lastInsertRowid)
  sqlite.prepare('INSERT INTO chapters(novel_id,chapter_num,content) VALUES(?,?,?)').run(otherNovelId, 1, '别书已保存正文。')
  let requests = 0, held = null
  const getAdapter = model.getAdapterById
  model.getAdapterById = () => ({ id: 'fixture', embed: async texts => {
    requests += 1
    if (held) await held.promise
    return texts.map((text, index) => [1, text.length / 2000, index / 10])
  } })
  const initial = rebuildChapterIndex({ novelId, throughChapter: 1 })
  assert.equal(initial.savedChapterCount, 1)
  assert.equal(initial.keywordIndexedChapterCount, 1)
  assert.equal(initial.vectorIndexedChapterCount, 0)
  assert.equal(requests, 0)
  assert.ok(sqlite.prepare('SELECT fragment_text FROM chapter_embeddings WHERE chapter_id=?').all(chapterId).some(row => row.fragment_text.includes('铜牌在中段箱底')))
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM chapter_embeddings WHERE chapter_id=?').get(futureId).n, 0)
  assert.equal(getChapterIndexStatus(otherNovelId).savedChapterCount, 1)

  const registry = new AgentToolRegistry()
  registerChapterIndexTools(registry)
  const context = { actor: { type: 'api_client', actorId: 'fixture', clientId: 'fixture' }, scopes: [...DESKTOP_AGENT_TOOL_SCOPES] }
  const statusCall = await registry.invoke({ toolId: 'novelforge.chapters.index_status', input: { novelId } }, context)
  assert.equal(statusCall.ok, true)
  const rebuildCall = await registry.invoke({ toolId: 'novelforge.chapters.index_rebuild', input: { novelId, throughChapter: 1, vectors: true } }, context)
  assert.equal(rebuildCall.ok, true)
  assert.equal(requests, 0, 'request returns before background vector work')
  let release
  held = { promise: new Promise(resolve => { release = resolve }) }
  const oldDrain = processSemanticMemoryOutbox({ novelId, limit: 10, allowRemoteEmbeddings: false })
  await new Promise(resolve => setImmediate(resolve))
  assert.equal(requests, 1, 'explicit vectors=true authorization survives the worker default')
  sqlite.prepare('UPDATE chapters SET content=?,context_version=context_version+1 WHERE id=?').run('刚保存的新正文：铜牌移到门边。', chapterId)
  const queued = sqlite.prepare("SELECT revision,status,operation FROM semantic_memory_outbox WHERE novel_id=? AND source_type='chapter' AND source_id=?").get(novelId, chapterId)
  assert.equal(queued.status, 'pending')
  assert.equal(queued.operation, 'upsert', 'a new save does not inherit remote authorization for the old source')
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM chapter_embeddings WHERE chapter_id=? AND embedding_json IS NOT NULL').get(chapterId).n, 0)
  held = null; release()
  const stale = await oldDrain
  assert.equal(stale.supersededCount, 1)
  assert.equal(sqlite.prepare("SELECT revision FROM semantic_memory_outbox WHERE source_type='chapter' AND source_id=?").get(chapterId).revision, queued.revision)
  assert.equal(sqlite.prepare('SELECT fragment_text FROM chapter_embeddings WHERE chapter_id=?').get(chapterId).fragment_text, '刚保存的新正文：铜牌移到门边。')
  rebuildChapterIndex({ novelId, vectors: true })
  assert.equal((await processSemanticMemoryOutbox({ novelId, limit: 10, allowRemoteEmbeddings: false })).processedCount, 1)
  assert.equal(getChapterIndexStatus(novelId).vectorIndexedChapterCount, 1)
  const existingVector = sqlite.prepare('SELECT embedding_json,source_hash FROM chapter_embeddings WHERE chapter_id=?').get(chapterId)
  rebuildChapterIndex({ novelId, vectors: false })
  assert.equal(getChapterIndexStatus(novelId).vectorIndexedChapterCount, 1, 'text-only repair preserves ready vectors')
  sqlite.prepare('UPDATE novels SET model_config_id=999999 WHERE id=?').run(novelId)
  rebuildChapterIndex({ novelId, vectors: false })
  assert.deepEqual(sqlite.prepare('SELECT embedding_json,source_hash FROM chapter_embeddings WHERE chapter_id=?').get(chapterId), existingVector, 'text-only repair preserves vector provenance even after the selected model disappears')
  sqlite.prepare('UPDATE novels SET model_config_id=? WHERE id=?').run(modelId, novelId)
  sqlite.prepare('UPDATE chapters SET chapter_num=3 WHERE id=?').run(chapterId)
  assert.equal(getChapterIndexStatus(novelId).vectorIndexedChapterCount, 1, 'reordering keeps the same saved prose index')

  rebuildChapterIndex({ novelId, vectors: true })
  sqlite.prepare("UPDATE semantic_memory_outbox SET status='processing',locked_at=datetime('now','-7 minutes') WHERE novel_id=? AND source_type='chapter'").run(novelId)
  assert.equal((await processSemanticMemoryOutbox({ novelId, limit: 10 })).processedCount, 1, 'orphaned leases recover without a new save')
  rebuildChapterIndex({ novelId, vectors: true })
  sqlite.prepare("UPDATE semantic_memory_outbox SET status='processing',attempts=8,locked_at=datetime('now','-7 minutes') WHERE novel_id=? AND source_type='chapter'").run(novelId)
  assert.equal((await processSemanticMemoryOutbox({ novelId, limit: 10 })).claimedCount, 0)
  assert.equal(getChapterIndexStatus(novelId).queue.dead_letter, 1, 'exhausted orphan work is visibly stopped instead of stuck pending forever')

  rebuildChapterIndex({ novelId, vectors: true })
  sqlite.prepare('UPDATE novels SET model_config_id=999999 WHERE id=?').run(novelId)
  assert.doesNotThrow(() => rebuildChapterIndex({ novelId, vectors: true }), 'writing model does not control retrieval')
  sqlite.prepare("UPDATE embedding_settings SET model_config_id=999999 WHERE id=1").run()
  assert.doesNotThrow(() => rebuildChapterIndex({ novelId, vectors: false }), 'bad vector credentials cannot block text repair')
  assert.throws(() => rebuildChapterIndex({ novelId, vectors: true }), /模型配置.*(不存在|失效)/)
  assert.equal((await processSemanticMemoryOutbox({ novelId, limit: 10 })).failedCount, 1)
  assert.match(getChapterIndexStatus(novelId).errors[0].message, /模型配置.*(不存在|失效)/)
  assert.equal(getChapterIndexStatus(novelId).keywordFallbackAvailable, true)
  sqlite.prepare('UPDATE novels SET model_config_id=? WHERE id=?').run(modelId, novelId)
  settings.setEmbeddingSettings({ mode: 'remote', modelConfigId: modelId, modelId: 'fixture-vector' })
  rebuildChapterIndex({ novelId, vectors: true })
  const generate = embedding.generateChapterEmbeddings
  embedding.generateChapterEmbeddings = async () => ({ applied: true, documentCount: 1, vectorizedCount: 0, source: 'unavailable' })
  assert.equal((await processSemanticMemoryOutbox({ novelId, limit: 10 })).failedCount, 1)
  assert.match(getChapterIndexStatus(novelId).errors[0].message, /文字检索已保存/)
  embedding.generateChapterEmbeddings = generate
  sqlite.prepare("UPDATE chapters SET content='' WHERE id=?").run(chapterId)
  assert.equal(sqlite.prepare('SELECT COUNT(*) AS n FROM chapter_embeddings WHERE chapter_id=?').get(chapterId).n, 0)
  assert.equal(getChapterIndexStatus(novelId).queue.failed, 0)
  sqlite.prepare('UPDATE chapters SET content=? WHERE id=?').run('重新保存正文。', chapterId)
  sqlite.prepare('DELETE FROM chapters WHERE id=?').run(chapterId)
  assert.equal(sqlite.prepare("SELECT COUNT(*) AS n FROM semantic_memory_outbox WHERE source_type='chapter' AND source_id=?").get(chapterId).n, 0)
  assert.equal(getChapterIndexStatus(novelId).savedChapterCount, 0)
  model.getAdapterById = getAdapter
  closeDb()
  console.log('[chapter-index] persisted queue, full prose, stale reply, restart lease, MCP scopes, invalid model, delete and reorder passed (fixture only)')
}
main().then(() => app.exit(0)).catch(error => { console.error(error); app.exit(1) })
