const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { app, BrowserWindow } = require('electron')
const { buildSync } = require('esbuild')
const root = path.resolve(__dirname, '..')
const temp = fs.mkdtempSync(path.join(root, '.tmp-tests', 'embedding-settings-ui-'))
app.setPath('userData', temp)
app.disableHardwareAcceleration()
async function main() {
  await app.whenReady()
  buildSync({ stdin: { contents: `import React from 'react';import{createRoot}from'react-dom/client';import EmbeddingSettings from './src/pages/AppSettings/EmbeddingSettings';window.calls=[];window.events=0;window.electron={agentTools:{call:request=>new Promise(resolve=>window.calls.push({request,resolve}))}};window.addEventListener('novelforge:embedding-settings-changed',()=>window.events++);const root=createRoot(document.getElementById('root'));window.unmount=()=>root.unmount();root.render(<EmbeddingSettings models={[{id:7,name:'连接',provider:'openai',modelId:'writing-model'}]}/>);`, loader: 'tsx', resolveDir: root }, bundle: true, platform: 'browser', outfile: path.join(temp, 'fixture.js') })
  fs.writeFileSync(path.join(temp, 'index.html'), '<div id="root"></div><script src="fixture.js"></script>')
  const win = new BrowserWindow({ show: false, webPreferences: { contextIsolation: false, nodeIntegration: false, backgroundThrottling: false } })
  await win.loadFile(path.join(temp, 'index.html'))
  const run = code => win.webContents.executeJavaScript(code)
  const wait = async code => { for (let i=0;i<100;i++) { if (await run(code)) return; await new Promise(resolve=>setTimeout(resolve,20)) }; throw Error('Timeout: '+code) }
  await wait('window.calls.length===1')
  await run(`window.calls[0].resolve({ok:true,data:{mode:'remote',modelConfigId:7,modelId:'vector-v1'}})`)
  await wait('!!document.querySelector("input[aria-label=\\"向量模型名称\\"]")')
  const edit = value => run(`{const input=document.querySelector('input[aria-label="向量模型名称"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(input,${JSON.stringify(value)});input.dispatchEvent(new Event('input',{bubbles:true}));}`)
  await edit('vector-v2')
  await wait('document.querySelector("input[aria-label=\\"向量模型名称\\"]").value==="vector-v2"')
  await run(`{const save=[...document.querySelectorAll('button')].find(button=>button.textContent.includes('保存检索配置'));save.click();save.click();}`)
  await wait('window.calls.length===2')
  assert.deepEqual(await run('window.calls[1].request.input'),{mode:'remote',modelConfigId:7,modelId:'vector-v2'})
  await new Promise(resolve=>setTimeout(resolve,40))
  assert.equal(await run('window.calls.length'),2,'rapid double submit sends one mutation')
  await run(`window.calls[1].resolve({ok:true,data:{mode:'remote',modelConfigId:7,modelId:'vector-v2'}})`)
  await wait('!!document.querySelector("[role=status]")')
  assert.equal(await run('window.events'),1)
  await edit('vector-v3')
  await wait('!document.querySelector("[role=status]")')
  await run(`{[...document.querySelectorAll('button')].find(button=>button.textContent.includes('保存检索配置')).click();}`)
  await wait('window.calls.length===3')
  await run('window.unmount()')
  await run(`window.calls[2].resolve({ok:true,data:{mode:'remote',modelConfigId:7,modelId:'vector-v3'}})`)
  await wait('window.events===2')
  assert.equal(await run('document.querySelector("#root").children.length'),0)
  win.destroy()
  console.log('[embedding-settings-ui] independent model name, duplicate submit lock, accurate saved state and completion after unmount passed (real ReactDOM)')
}
main().then(()=>app.exit(0)).catch(error=>{console.error(error);app.exit(1)})
