const path = require('node:path')
const { app } = require('electron')
const fs = require('node:fs')
const root = path.resolve(__dirname, '..')
app.setAppPath(root)
app.disableHardwareAcceleration()
const entry = path.join(root, 'out/main/main.js')
if (!fs.existsSync(entry)) {
  console.error('Build NovelForge first: npm run build:app')
  app.exit(1)
} else require(entry)
