const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { app } = require('electron')
const { registerProjectTsRuntime } = require('./register-project-ts.cjs')
const isolatedPath = fs.mkdtempSync(path.join(os.tmpdir(), 'novelforge-rf-policy-'))
process.env.NOVELFORGE_DISABLE_LEGACY_DB_COPY = '1'
process.env.NOVELFORGE_USER_DATA_DIR = isolatedPath
app.setPath('userData', isolatedPath)
registerProjectTsRuntime(path.resolve(__dirname, '..'))

app.whenReady().then(async () => {
  const { initDb, getSqlite, closeDb } = require('../electron/database/db.ts')
  try {
    initDb()
    let sqlite = getSqlite()
    const { updateNovel } = require('../electron/services/novel.service.ts')
    const { resolveChapterNarrativeIdentity, assertChapterNarrativeInputCurrent, currentNarrativeSceneIdentity } = require('../electron/services/chapter-narrative-policy.ts')
    const { ChapterPipelineRuntime } = require('../electron/services/chapter-pipeline-runtime.ts')
    const { getTaskRecord, updateTaskStatus } = require('../electron/services/task.service.ts')
    const { chapterGenerationInputIdentity } = require('../electron/services/chapter-generation-idempotency.ts')
    const { savePromptOverride, deletePromptOverride } = require('../electron/services/prompt-override.service.ts')
    const { listWorkflowNodeRuns, getWorkflowNodeSnapshot } = require('../electron/services/workflow-node.service.ts')
    const { resumeChapterPipeline, generateChapterContent, __testing } = require('../electron/services/chapter-generation.usecase.ts')
    const { getChapter } = require('../electron/services/chapter.service.ts')
    const novelId = Number(sqlite.prepare('INSERT INTO novels (title, settings_json) VALUES (?, ?)').run('RF policy fixture', '{"other":{"keep":7}}').lastInsertRowid)
    const chapterId = Number(sqlite.prepare('INSERT INTO chapters (novel_id, chapter_num, title, content, status) VALUES (?, ?, ?, ?, ?)').run(novelId, 1, '晚饭', '确认正文保留。', 'final').lastInsertRowid)
    // The formal entry bootstraps volume/part assignments before freezing identity.
    // Match that boundary before constructing an already-existing task fixture.
    require('../electron/services/story-structure.service.ts').ensureStoryStructure(novelId)
    const old = resolveChapterNarrativeIdentity(chapterId)
    assert.equal(old.policyVersion, 'legacy')
    updateNovel(novelId, { settingsJson: '{"readerFirst":{"schemaVersion":1,"policyVersion":"reader-first-v1","revision":1}}' })
    const identity = resolveChapterNarrativeIdentity(chapterId)
    assert.notEqual(chapterGenerationInputIdentity(old), chapterGenerationInputIdentity(identity))
    assert.equal(chapterGenerationInputIdentity(identity), chapterGenerationInputIdentity(resolveChapterNarrativeIdentity(chapterId)))
    const baseKey = () => __testing.buildChapterGenerationIdempotencyKey(getChapter(chapterId), undefined, identity)
    const idempotencyKey = `${baseKey()}:${chapterGenerationInputIdentity(identity)}`
    const runtime = await ChapterPipelineRuntime.create({ chapterId, novelId, narrativeIdentity: identity,
      idempotencyKey,
      executionMode: 'balanced', initialContent: '确认正文保留。', initialContextVersion: 2,
      buildRecoveryHint: () => ({ kind: 'open_page', label: '保留现稿并重新生成', description: '写作页', path: '/writing' }),
      getOutputRefs: () => ({ chapterId, contentHash: 'fixture', scenePlanHash: '', reviewNotesHash: '' }), onProgress() {} })
    assert.deepEqual(JSON.parse(getTaskRecord(runtime.workflowTaskId).progressJson).narrativeIdentity, identity)
    assert.equal(await generateChapterContent(chapterId), runtime.workflowTaskId)
    assert.equal(await generateChapterContent(chapterId), runtime.workflowTaskId)
    const roleId = await runtime.startRole({ role: 'writer', type: 'chapter_writer', detail: 'RF policy persistence', runnerType: 'workflow', inputJson: '[]' })
    updateTaskStatus(roleId, 'success', { outputText: 'isolated fixture' })
    runtime.finishRole('writer', roleId, 'isolated fixture complete')
    assert.deepEqual(JSON.parse(getTaskRecord(runtime.workflowTaskId).progressJson).narrativeIdentity, identity)
    assert.equal(listWorkflowNodeRuns({ workflowTaskId: runtime.workflowTaskId }).length, 1)
    closeDb()
    initDb()
    sqlite = getSqlite()
    assert.deepEqual(JSON.parse(getTaskRecord(runtime.workflowTaskId).progressJson).narrativeIdentity, identity)
    const persistedNode = listWorkflowNodeRuns({ workflowTaskId: runtime.workflowTaskId })[0]
    assert.deepEqual(getWorkflowNodeSnapshot(persistedNode.snapshotId).payload.narrativeIdentity, identity)
    assert.doesNotThrow(() => assertChapterNarrativeInputCurrent(chapterId, identity))
    const plan = JSON.stringify([{ scene_order: 1, purpose: '商量送饭' }])
    sqlite.prepare('UPDATE chapters SET scene_plan_json = ? WHERE id = ?').run(plan, chapterId)
    runtime.adoptSnapshot({ ...runtime.snapshot, partialContent: '确认正文保留。', lastFailureRole: 'writer',
      plannerScenePlanJson: plan, narrativeIdentity: currentNarrativeSceneIdentity(identity, plan) })
    runtime.sync()
    updateTaskStatus(runtime.workflowTaskId, 'cancelled')
    const originalTaskCount = sqlite.prepare('SELECT COUNT(*) AS count FROM tasks').get().count
    const rejectedResume = async (pattern) => {
      await assert.rejects(resumeChapterPipeline(runtime.workflowTaskId), pattern)
      assert.equal(sqlite.prepare('SELECT COUNT(*) AS count FROM tasks').get().count, originalTaskCount)
      assert.equal(sqlite.prepare('SELECT content FROM chapters WHERE id = ?').get(chapterId).content, '确认正文保留。')
    }
    sqlite.prepare('UPDATE chapters SET scene_plan_json = ? WHERE id = ?').run('[{"purpose":"改去远方"}]', chapterId)
    await rejectedResume(/不能混用旧稿恢复/)
    sqlite.prepare('UPDATE chapters SET scene_plan_json = ? WHERE id = ?').run(plan, chapterId)
    sqlite.prepare('UPDATE novels SET theme_voice_json = ? WHERE id = ?').run('{"humanStyleSampleLock":"改用近距离观察"}', novelId)
    await rejectedResume(/不能混用旧稿恢复/)
    sqlite.prepare('UPDATE novels SET theme_voice_json = NULL WHERE id = ?').run(novelId)
    savePromptOverride('chapterDraft', 'LITERAL: 每章至少一个代价。{chapterTitle}')
    assert.throws(() => assertChapterNarrativeInputCurrent(chapterId, identity), /不能混用旧稿恢复/)
    await rejectedResume(/不能混用旧稿恢复/)
    const { createChapterStagePrepareInput } = require('../electron/services/chapter-pipeline-context.ts')
    const customContext = { narrativeIdentity: resolveChapterNarrativeIdentity(chapterId), contextPack: { chapterId, contextVersion: 2, sources: [] } }
    const customMessages = [{ role: 'user', content: 'LITERAL: 每章至少一个代价。$KEEP [原样]' }]
    const prepared = createChapterStagePrepareInput(customContext, 'draft')({ messages: customMessages,
      budgetReport: { allowed: false, effectiveBudget: 1, estimatedTotalTokens: 1000 } })
    assert.deepEqual(prepared.messages, customMessages)
    assert.equal(prepared.diagnostics.promptSource.source, 'custom')
    assert.equal(prepared.diagnostics.promptSource.scope, 'global-template')
    assert.match(prepared.diagnostics.finalMessagesHash, /^sha256:/)
    deletePromptOverride('chapterDraft')
    const beforeModel = resolveChapterNarrativeIdentity(chapterId)
    sqlite.prepare('INSERT INTO model_configs (name, provider, model_id) VALUES (?, ?, ?)').run('local test', 'openai', 'mock-model')
    assert.throws(() => assertChapterNarrativeInputCurrent(chapterId, beforeModel), /不能混用旧稿恢复/)
    await rejectedResume(/不能混用旧稿恢复/)
    runtime.adoptSnapshot({ ...runtime.snapshot, narrativeIdentity: undefined })
    runtime.sync()
    await rejectedResume(/从 Planner 新建任务/)
    const currentIdentity = resolveChapterNarrativeIdentity(chapterId)
    const beforeAssetEditKey = baseKey()
    sqlite.prepare('UPDATE novels SET context_version = context_version + 1 WHERE id = ?').run(novelId)
    assert.notEqual(baseKey(), beforeAssetEditKey)
    assert.throws(() => assertChapterNarrativeInputCurrent(chapterId, currentIdentity, 2), { code: 'chapter.pipelineContextConflict' })
    updateNovel(novelId, { settingsJson: '{"readerFirst":{"schemaVersion":1,"policyVersion":"legacy","revision":2}}' })
    assert.equal(resolveChapterNarrativeIdentity(chapterId).policyVersion, 'legacy')
    const settings = JSON.parse(sqlite.prepare('SELECT settings_json FROM novels WHERE id = ?').get(novelId).settings_json)
    assert.deepEqual(settings.other, { keep: 7 })
    assert.equal(sqlite.prepare('SELECT content FROM chapters WHERE id = ?').get(chapterId).content, '确认正文保留。')
    assert.throws(() => updateNovel(novelId, { settingsJson: '{"readerFirst":{"schemaVersion":1,"policyVersion":"reader-first-v1","revision":1}}' }), /请刷新设置/)
    console.log(JSON.stringify({ status: 'PASS', cases: ['RF-05-01', 'RF-05-02', 'RF-05-03', 'RF-05-04'], reopenedDatabase: true, workflowTaskId: runtime.workflowTaskId, userData: isolatedPath, realModelCalls: 0 }))
    closeDb()
    fs.rmSync(isolatedPath, { recursive: true, force: true })
    app.exit(0)
  } catch (error) { console.error(error); closeDb(); app.exit(1) }
}).catch((error) => { console.error(error); app.exit(1) })
