const assert = require('node:assert/strict')
const fs = require('node:fs')
const os = require('node:os')
const path = require('node:path')
const { app } = require('electron')
const { registerProjectTsRuntime } = require('./register-project-ts.cjs')

// A new userData path is selected before readiness; never use the desktop database.
const isolatedPath = fs.mkdtempSync(path.join(os.tmpdir(), 'novelforge-rf-storage-'))
process.env.NOVELFORGE_DISABLE_LEGACY_DB_COPY = '1'
process.env.NOVELFORGE_USER_DATA_DIR = isolatedPath
app.setPath('userData', isolatedPath)
registerProjectTsRuntime(path.resolve(__dirname, '..'))

app.whenReady().then(() => {
  const { initDb, getSqlite } = require('../electron/database/db.ts')
  let sqlite
  try {
    initDb()
    sqlite = getSqlite()
    const style = require('../electron/services/style-analysis.service.ts')
    const { updateNovel } = require('../electron/services/novel.service.ts')
    const { preserveStyleApproval } = require('../src/shared/style-source.ts')
    const novelId = Number(sqlite.prepare('INSERT INTO novels (title, settings_json) VALUES (?, ?)').run('RF isolated fixture', '{"other":7}').lastInsertRowid)
    const otherId = Number(sqlite.prepare('INSERT INTO novels (title) VALUES (?)').run('Other fixture').lastInsertRowid)
    const insert = sqlite.prepare('INSERT INTO style_fingerprints (novel_id, name, source_text, fingerprint_json, source_type) VALUES (?, ?, ?, ?, ?)')
    const fingerprint = JSON.stringify(style.getDefaultFingerprint())
    const first = Number(insert.run(novelId, 'candidate', '姐姐把袋子放在床边。弟弟没接。', fingerprint, 'pasted').lastInsertRowid)
    insert.run(novelId, 'new automatic candidate', '自动采样候选。', fingerprint, 'chapters')
    assert.equal(style.resolveActiveStyleFingerprint(novelId), null, 'automatic candidate must not become active')
    style.setActiveStyleFingerprint(novelId, first)
    assert.equal(style.resolveActiveStyleFingerprint(novelId).approvedSample.text, '姐姐把袋子放在床边。弟弟没接。')
    const readNovel = () => sqlite.prepare('SELECT * FROM novels WHERE id = ?').get(novelId)
    assert.equal(JSON.parse(readNovel().settings_json).other, 7)
    insert.run(novelId, 'new auto candidate', '雨停了。他收起伞。', fingerprint, 'chapters')
    assert.equal(style.resolveActiveStyleFingerprint(novelId).record.id, first)
    const sourceSettings = readNovel().settings_json
    const forged = preserveStyleApproval(sourceSettings, '{"other":8,"styleSourceApproval":{"version":1,"status":"approved","digest":"forged","approvedAt":"now"}}')
    assert.equal(JSON.parse(forged).styleSourceApproval.digest, JSON.parse(sourceSettings).styleSourceApproval.digest)
    updateNovel(novelId, { settingsJson: '{"other":9,"styleSourceApproval":{"digest":"forged"}}' })
    assert.equal(JSON.parse(readNovel().settings_json).other, 9)
    assert.equal(style.resolveActiveStyleFingerprint(novelId).record.id, first)
    sqlite.prepare('UPDATE style_fingerprints SET source_text = ? WHERE id = ?').run('已被修改。', first)
    assert.equal(style.resolveActiveStyleFingerprint(novelId), null, 'modified approved source is invalid')
    style.setActiveStyleFingerprint(novelId, first)
    style.setActiveStyleFingerprint(novelId, null)
    assert.equal(style.resolveActiveStyleFingerprint(novelId), null, 'revoke must not fall back to latest')
    const chapterId = Number(sqlite.prepare('INSERT INTO chapters (novel_id, chapter_num, title, content) VALUES (?, ?, ?, ?)').run(novelId, 1, '原文', '母亲放下杯子。').lastInsertRowid)
    const sampled = Number(insert.run(novelId, 'chapter sample', '母亲放下杯子。', fingerprint, 'chapters').lastInsertRowid)
    sqlite.prepare('UPDATE style_fingerprints SET source_chapter_ids_json = ? WHERE id = ?').run(JSON.stringify([chapterId]), sampled)
    style.setActiveStyleFingerprint(novelId, sampled)
    assert.equal(style.resolveActiveStyleFingerprint(novelId).record.id, sampled)
    sqlite.prepare('UPDATE chapters SET content = ? WHERE id = ?').run('母亲拿起杯子。', chapterId)
    assert.equal(style.resolveActiveStyleFingerprint(novelId), null)
    assert.deepEqual(style.resolveAuthorStyleMaterial(novelId).styleSourceDiagnostics, ['source_chapter_changed'])
    const foreign = Number(insert.run(otherId, 'foreign', '别的作品。', fingerprint, 'pasted').lastInsertRowid)
    assert.throws(() => style.setActiveStyleFingerprint(novelId, foreign))
    style.setActiveStyleFingerprint(novelId, first)
    sqlite.prepare('DELETE FROM style_fingerprints WHERE id = ?').run(first)
    assert.equal(style.resolveActiveStyleFingerprint(novelId), null, 'deleted source must not fall back')
    console.log(JSON.stringify({ status: 'PASS', cases: ['RF-03-02', 'RF-03-03', 'RF-03-04'], userData: isolatedPath, realModelCalls: 0 }))
    sqlite.close()
    fs.rmSync(isolatedPath, { recursive: true, force: true })
    app.exit(0)
  } catch (error) {
    console.error(error)
    if (sqlite?.open) sqlite.close()
    app.exit(1)
  }
}).catch((error) => { console.error(error); app.exit(1) })
