const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { app } = require('electron')
const root = path.resolve(__dirname, '..')
const profile = fs.mkdtempSync(path.join(root, '.tmp-tests', 'sqlite-vec-retrieval-'))
app.setPath('userData', profile)
app.disableHardwareAcceleration()
process.env.NOVELFORGE_DISABLE_LEGACY_DB_COPY = '1'
require(path.join(root, 'scripts/register-project-ts.cjs')).registerProjectTsRuntime(root)
async function main() {
  await app.whenReady()
  const db = require(path.join(root, 'electron/database/db.ts'))
  db.initDb()
  const sql = db.getSqlite()
  const embedding = require(path.join(root, 'electron/services/embedding.service.ts'))
  const { hashQueryText } = require(path.join(root, 'electron/services/query-embedding.ts'))
  const { getChapterIndexStatus } = require(path.join(root, 'electron/services/chapter-index.service.ts'))
  const novelId = Number(sql.prepare('INSERT INTO novels(title) VALUES(?)').run('Isolated retrieval audit').lastInsertRowid)
  const ids = []
  sql.transaction(() => {
    for (let n = 1; n <= 801; n++) {
      const prose = n === 1 ? '木匣曾被封进墙里。' : `石阶上的脚印属于第${n}章。`
      const id = Number(sql.prepare('INSERT INTO chapters(novel_id,chapter_num,content) VALUES(?,?,?)').run(novelId,n,prose).lastInsertRowid)
      ids.push(id)
      sql.prepare('DELETE FROM chapter_embeddings WHERE chapter_id=?').run(id)
      sql.prepare('INSERT INTO chapter_embeddings(novel_id,chapter_id,fragment_type,fragment_text,embedding_json,embedding_profile,dimensions,model_id,visibility) VALUES(?,?,?,?,?,?,?,?,?)')
        .run(novelId,id,'content_excerpt',prose,n === 1 ? '[1,0]' : '[0,1]','fixture-a:2',2,'fixture-a','canon')
    }
  })()
  const query='封存容器'
  const exactBest=ids[0]
  const result=await embedding.searchSimilarFragments(novelId,query,3,undefined,{beforeChapterNum:900,preparedQuery:{queryHash:hashQueryText(query),profile:'fixture-a:2',dimensions:2,embedding:[1,0]}})
  const mixedQuery='石阶'
  const mixed=await embedding.searchSimilarFragments(novelId,mixedQuery,3,undefined,{beforeChapterNum:900,preparedQuery:{queryHash:hashQueryText(mixedQuery),profile:'fixture-b:2',dimensions:2,embedding:[1,0]}})
  assert.equal(result.hits[0].chapterId, exactBest, 'all history is searched, including chapter one beyond the old 768 cap')
  assert.equal(mixed.fallbackReason, 'embedding_profile_mismatch')
  console.log('AUDIT_RESULT '+JSON.stringify({fixtureOnly:true,realProviderCalls:0,vectorEngine:getChapterIndexStatus(novelId).vectorEngine,vectorTableCount:sql.prepare("SELECT count(*) AS n FROM sqlite_master WHERE name LIKE 'chapter_vec_%' AND sql LIKE 'CREATE VIRTUAL%'").get().n,historyShortlist:{globallyBestChapter:exactBest,returnedChapters:result.hits.map(hit=>hit.chapterId),missedBest:!result.hits.some(hit=>hit.chapterId===exactBest)},statusMismatch:{displayedReady:getChapterIndexStatus(novelId).vectorIndexedChapterCount,actualSearchModes:mixed.hits.map(hit=>hit.searchMode),fallbackReason:mixed.fallbackReason}}))

  const native = require(path.join(root, 'electron/database/chapter-vector-index.ts'))
  const lookup = (before=900) => native.searchChapterVectors(db.getSqlite(), { novelId, profile:'fixture-a:2', dimensions:2, vector:[1,0], topK:3, beforeChapterNum:before, proseOnly:true })
  assert.equal(lookup()[0].chapterId, exactBest)
  sql.prepare('UPDATE chapter_embeddings SET embedding_json=? WHERE chapter_id=?').run('[0.1,1]',exactBest)
  assert.ok(lookup()[0].distance > 0, 'update replaces index vector')
  sql.prepare('UPDATE chapter_embeddings SET embedding_json=? WHERE chapter_id=?').run('[1,0]',exactBest)
  sql.prepare('UPDATE chapters SET chapter_num=850 WHERE id=?').run(exactBest)
  assert.ok(!lookup(800).some(row=>row.chapterId===exactBest), 'chapter filtering uses current order before KNN')
  sql.prepare('UPDATE chapters SET chapter_num=1 WHERE id=?').run(exactBest)
  assert.equal(lookup(2)[0].chapterId,exactBest)
  const otherNovel = Number(sql.prepare('INSERT INTO novels(title) VALUES(?)').run('隔离书').lastInsertRowid)
  const otherChapter = Number(sql.prepare('INSERT INTO chapters(novel_id,chapter_num,content) VALUES(?,?,?)').run(otherNovel,1,'异书同类线索').lastInsertRowid)
  sql.prepare('INSERT INTO chapter_embeddings(novel_id,chapter_id,fragment_type,fragment_text,embedding_json,embedding_profile,dimensions) VALUES(?,?,?,?,?,?,?)').run(otherNovel,otherChapter,'content_excerpt','异书同类线索','[1,0]','fixture-a:2',2)
  assert.ok(lookup().every(row=>row.chapterId!==otherChapter),'cross-project vectors never leak')
  sql.prepare('UPDATE chapter_embeddings SET embedding_json=? WHERE chapter_id=?').run('[0,0]',exactBest)
  assert.ok(!lookup().some(row=>row.chapterId===exactBest),'zero vectors rejected without breaking ordinary updates')
  sql.prepare('UPDATE chapter_embeddings SET embedding_json=? WHERE chapter_id=?').run('malformed',exactBest)
  assert.ok(!lookup().some(row=>row.chapterId===exactBest),'malformed historic vectors excluded')
  sql.prepare('UPDATE chapter_embeddings SET embedding_json=? WHERE chapter_id=?').run('[1,0]',exactBest)
  db.closeDb(); db.initDb()
  assert.equal(lookup()[0].chapterId,exactBest,'reopen reconciles native cache')
  db.closeDb()
  const Database = require('better-sqlite3')
  const withoutDll = new Database(path.join(profile,'novelforge.db'))
  withoutDll.loadExtension = () => {throw new Error('fixture missing DLL')}
  assert.equal(native.vectorExtensionStatus(withoutDll).version,null)
  withoutDll.prepare('UPDATE chapters SET content=? WHERE id=?').run('扩展故障期间保存的文字',exactBest)
  assert.equal(withoutDll.prepare('SELECT content FROM chapters WHERE id=?').get(exactBest).content,'扩展故障期间保存的文字')
  withoutDll.close()
  db.initDb()
  assert.ok(!lookup().some(row=>row.chapterId===exactBest),'offline edits invalidate stale vectors on reopen')
  const current = db.getSqlite()
  const memoryInsert = current.prepare('INSERT INTO semantic_memory_entries(novel_id,source_type,source_id,fragment_key,content_text,embedding_json,dimensions,embedding_profile,source_hash,visibility,valid_from_chapter) VALUES(?,?,?,?,?,?,?,?,?,?,?)')
  current.transaction(()=>{ for(let i=1;i<=700;i++) memoryInsert.run(novelId,'item',i,'fixture',i===1?'木匣曾被封进墙里。':'石阶上的脚印',i===1?'[1,0]':'[0,1]',2,'fixture-a:2','fixture','canon',1) })()
  memoryInsert.run(novelId,'item',701,'fixture','未来的容器','[1,0]',2,'fixture-a:2','fixture','canon',100)
  const memory = require(path.join(root,'electron/services/semantic-memory.service.ts'))
  const historicalMemory = await memory.searchSemanticMemory(novelId,query,{topK:1,chapterNum:50,sourceTypes:['item'],refreshOutbox:false,preparedQuery:{queryHash:hashQueryText(query),profile:'fixture-a:2',dimensions:2,embedding:[1,0]}})
  assert.equal(historicalMemory[0].sourceId,1,'structured semantic recall also searches early, valid historical projections without lexical overlap')
  const model = require(path.join(root,'electron/services/model.service.ts'))
  const settings = require(path.join(root,'electron/services/embedding-settings.service.ts'))
  const modelId = Number(db.getSqlite().prepare('INSERT INTO model_configs(name,provider,model_id,api_key,base_url) VALUES(?,?,?,?,?)').run('向量连接','openai','chat-v1',model.encryptApiKey('fixture'),'http://localhost/vector-fixture').lastInsertRowid)
  settings.setEmbeddingSettings({mode:'remote',modelConfigId:modelId,modelId:'vector-v1'})
  const identity = settings.embeddingRuntimeIdentity()
  db.getSqlite().prepare('UPDATE model_configs SET model_id=? WHERE id=?').run('chat-v2',modelId)
  assert.equal(settings.embeddingRuntimeIdentity().key,identity.key,'writing model switch leaves vector identity unchanged')
  db.getSqlite().prepare('UPDATE chapter_embeddings SET embedding_profile=?,model_id=? WHERE chapter_id=?').run(identity.modelId+':2',identity.modelId,ids[1])
  assert.equal(getChapterIndexStatus(novelId).vectorIndexedChapterCount,1)
  db.getSqlite().prepare('INSERT INTO chapter_embeddings(novel_id,chapter_id,fragment_type,fragment_text) VALUES(?,?,?,?)').run(novelId,ids[1],'content_excerpt:1','尚未向量化的第二片段')
  assert.equal(getChapterIndexStatus(novelId).vectorIndexedChapterCount,0,'partial NULL fragments cannot display ready')
  settings.setEmbeddingSettings({mode:'remote',modelConfigId:modelId,modelId:'vector-v2'})
  assert.notEqual(settings.embeddingRuntimeIdentity().key,identity.key)
  assert.equal(getChapterIndexStatus(novelId).vectorIndexedChapterCount,0)
  assert.throws(()=>settings.setEmbeddingSettings({mode:'remote',modelConfigId:999999,modelId:'vector-v1'}))
  settings.setEmbeddingSettings({mode:'local',modelConfigId:null,modelId:''})
  db.closeDb()
  console.log('[sqlite-vec] full history, scoped KNN, insert/update/delete/reorder/reopen, missing DLL fallback, profile status and independent model settings passed; synthetic vectors, no provider calls')

}
main().then(()=>app.quit()).catch(error=>{console.error(error);app.exit(1)})
