const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { app, safeStorage } = require('electron')
const { registerProjectTsRuntime } = require('./register-project-ts.cjs')
const root = path.resolve(__dirname, '..')
fs.mkdirSync(path.join(root, '.tmp-tests'), { recursive: true })
const temp = fs.mkdtempSync(path.join(root, '.tmp-tests', 'zhuque-'))
app.setPath('userData', temp)
app.disableHardwareAcceleration()
process.env.NOVELFORGE_DISABLE_LEGACY_DB_COPY = '1'
registerProjectTsRuntime(root)
const delay = ms => new Promise(resolve => setTimeout(resolve, ms))
async function main() {
  await app.whenReady()
  const db = require('../electron/database/db.ts')
  db.initDb()
  const chapter = require('../electron/services/chapter.service.ts')
  const novel = require('../electron/services/novel.service.ts')
  const detector = require('../electron/services/zhuque-detection.service.ts')
  const calls = []
  globalThis.fetch = async (url, options) => {
    assert.equal(url, 'https://ai-gateway.edgeone.link/v1/providers/zhuque-text/classify')
    assert.equal(options.redirect, 'error')
    const body = JSON.parse(options.body)
    calls.push(body)
    return { ok: true, json: async () => ({ status: 'success', labels_ratio: { '0': 0.1, '1': 0.4, '2': 0.5 }, softmax_confidence: 0.8, ratio_confidence: 0.9,
      segment_labels: [{ text: body.text, label: 1, conf: 0.8 }], makers_models_usage: { total_tokens: 60 } }) }
  }
  try {
    const novelId = novel.createNovel({ title: '朱雀隔离试验' })
    const id = chapter.createChapter(novelId, { title: '正文', chapterNum: 1 })
    assert.deepEqual(detector.getZhuqueSettings(), { enabled: false, autoDetect: true, apiKeySet: false })
    chapter.updateChapter(id, { content: '关闭检测时保存正文，不发起调用。' })
    await delay(1700); assert.equal(calls.length, 0)
    if (!safeStorage.isEncryptionAvailable()) throw new Error('本机安全存储不可用，无法完成加密配置回归。')
    const key = 'zhuque-fixture-key-not-a-real-credential'
    assert.deepEqual(detector.updateZhuqueSettings({ enabled: true, apiKey: key }), { enabled: true, autoDetect: true, apiKeySet: true })
    const settingsPath = path.join(temp, 'local-zhuque', 'credentials.json')
    assert.equal(fs.readFileSync(settingsPath, 'utf8').includes(key), false)
    const stored = JSON.parse(fs.readFileSync(settingsPath, 'utf8'))
    assert.equal(safeStorage.decryptString(Buffer.from(stored.encryptedKey, 'base64')), key)
    assert.equal(fs.readFileSync(path.join(temp, 'novelforge.db')).includes(Buffer.from(key)), false)
    assert.throws(() => db.getSqlite().transaction(() => { chapter.updateChapter(id, { content: '这一段事务会回滚，不得上传。' }); throw Error('rollback') })(), /rollback/)
    await delay(1700); assert.equal(calls.length, 0)
    chapter.updateChapter(id, { content: '已提交的完整正文，包含开头。\n\n这也是末尾，必须完整送检。' })
    chapter.updateChapter(id, { summary: '只更新摘要不检测。' })
    await delay(1800)
    assert.equal(calls.length, 1)
    assert.equal(calls[0].text, chapter.getChapter(id).content)
    assert.equal(calls[0].is_merge, false)
    const report = detector.getZhuqueChapterResult(id)
    assert.equal(report.status, 'success'); assert.equal(report.report.metrics.aiRatio, 0.4)
    assert.equal(report.report.metrics.suspectedAiRatio, 0.5)
    assert.equal(JSON.stringify(report).includes(key), false)
    await detector.detectZhuqueChapter(id); assert.equal(calls.length, 1, 'same-version success is cached')
    detector.updateZhuqueSettings({ enabled: false })
    chapter.updateChapter(id, { content: '再次修改正文，开关关闭。' })
    assert.equal(detector.getZhuqueChapterResult(id).status, 'stale')
    await delay(1700); assert.equal(calls.length, 1)
    detector.updateZhuqueSettings({ enabled: true, autoDetect: false })
    chapter.updateChapter(id, { content: '手动检测模式下的新正文。' })
    await delay(1700); assert.equal(calls.length, 1)
    await detector.detectZhuqueChapter(id); assert.equal(calls.length, 2)
    detector.updateZhuqueSettings({ enabled: false, apiKey: '' })
    assert.equal(detector.getZhuqueSettings().apiKeySet, false)
    console.log('PASS Zhuque: actual Electron encryption/local-only credentials, full saved prose, transaction rollback, auto/manual/off modes, version cache and stale results. Mock provider; zero real Tencent requests.')
  } finally { detector.updateZhuqueSettings({ enabled: false }); db.closeDb() }
}
main().then(() => app.exit(0)).catch(error => { console.error(error); app.exit(1) })
