const assert = require('node:assert/strict')
const fs = require('node:fs')
const path = require('node:path')
const { createHash } = require('node:crypto')
const { app, BrowserWindow } = require('electron')
const { buildSync } = require('esbuild')
const root = path.resolve(__dirname, '..')
fs.mkdirSync(path.join(root, '.tmp-tests'), { recursive: true })
const temp = fs.mkdtempSync(path.join(root, '.tmp-tests', 'zhuque-ui-'))
app.setPath('userData', temp); app.disableHardwareAcceleration()
async function main() {
  await app.whenReady()
  const contents = [
    "import React from 'react';import{createRoot}from'react-dom/client';",
    "import{ConfigProvider}from'antd';import{getAntdThemeConfig}from'./src/theme/antd-tokens';import'./src/styles/global.css';import'./src/styles/ui-simplification.css';import'./src/pages/ModelManager/index.css';",
    "import ZhuqueSettings from './src/pages/ModelManager/ZhuqueSettings';",
    "import ZhuqueChapterPanel from './src/components/ZhuqueChapterPanel';",
    "import Manuscript from './src/pages/Novel/AuthorWorkspace/Manuscript';import{MemoryRouter}from'react-router-dom';",
    "window.calls=[];window.electron={zhuque:{getSettings:()=>Promise.resolve({enabled:false,autoDetect:true,apiKeySet:false}),",
    "updateSettings:input=>new Promise((resolve,reject)=>window.calls.push({kind:'settings',input,resolve,reject})),",
    "test:()=>new Promise(resolve=>window.calls.push({kind:'test',resolve})),",
    "getChapterResult:id=>new Promise(resolve=>window.calls.push({kind:'read',id,resolve})),",
    "detectChapter:(id,expectedContent)=>new Promise(resolve=>window.calls.push({kind:'detect',id,expectedContent,resolve}))},",
    "chapter:{list:()=>Promise.resolve([{id:1,novelId:1,chapterNum:1,title:'第一章',content:'已保存的正文。',wordCount:7}]),get:()=>Promise.resolve({id:1,novelId:1,chapterNum:1,title:'第一章',content:'已保存的正文。',wordCount:7})},agentTools:{call:()=>Promise.resolve({ok:true,data:{run:null}})}};",
    "const root=createRoot(document.getElementById('root'));window.editor='已保存的正文。';",
    "const frame=children=><ConfigProvider theme={getAntdThemeConfig('light')}><div className='app-layout' data-ui-system='quiet-workspace'>{children}</div></ConfigProvider>;window.showSettings=()=>root.render(frame(<div className='model-manager-page' style={{padding:32,width:'100%'}}><ZhuqueSettings/></div>));",
    "window.showManuscript=()=>root.render(frame(<MemoryRouter initialEntries={['/novel/1/writing?chapterId=1']}><Manuscript novelId={1}/></MemoryRouter>));",
    'window.showChapter=id=>root.render(<ZhuqueChapterPanel chapterId={id} savedContent="已保存的正文。" getContent={()=>window.editor}/>);window.showSettings();',
  ].join('')
  buildSync({ stdin: { contents, loader: 'tsx', resolveDir: root }, bundle: true, platform: 'browser', outfile: path.join(temp, 'fixture.js') })
  fs.writeFileSync(path.join(temp, 'index.html'), '<meta charset="utf-8"><link rel="stylesheet" href="fixture.css"><div id="root"></div><script src="fixture.js"></script>')
  const win = new BrowserWindow({ show: false, width:1180, height:820, webPreferences: { offscreen:true, contextIsolation: false, nodeIntegration: false, backgroundThrottling: false } })
  win.webContents.on('console-message', (_event, level, message) => { if (level >= 2) console.error('[renderer]', message) })
  await win.loadFile(path.join(temp, 'index.html'))
  const run = code => win.webContents.executeJavaScript(code)
  const wait = async code => { for (let i = 0; i < 150; i++) { if (await run(code)) return; await new Promise(resolve => setTimeout(resolve, 20)) } throw Error('Timeout: '+code) }
  const click = text => run("{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==="+JSON.stringify(text)+");if(!b)throw Error('button absent');b.click();}")
  const screenshot = async name => { await run('new Promise(resolve=>requestAnimationFrame(()=>requestAnimationFrame(resolve)))'); await new Promise(resolve=>setTimeout(resolve,300)); fs.writeFileSync(path.join(temp, name+'.png'), (await win.webContents.capturePage()).toPNG()) }
  await wait('!!document.querySelector("[data-zhuque-settings]") && ![...document.querySelectorAll("button")].find(b=>b.textContent.includes("配置朱雀检测")).disabled')
  await click('配置朱雀检测')
  await wait("!!document.querySelector('input[aria-label=\"朱雀 API Key\"]')")
  await screenshot('settings')
  const testDisabled = "[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='保存并测试').disabled"
  const changeKey = value => run("{const i=document.querySelector('input[aria-label=\"朱雀 API Key\"]');Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,'value').set.call(i,"+JSON.stringify(value)+");i.dispatchEvent(new Event('input',{bubbles:true}));}")
  assert.equal(await run(testDisabled), true, 'missing credentials disable connection testing')
  await changeKey('fixture-ui-key')
  await wait("document.querySelector('input[aria-label=\"朱雀 API Key\"]').value==='fixture-ui-key'")
  await wait('!'+testDisabled)
  await run("{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='保存并测试');b.click();b.click();}")
  await wait('window.calls.filter(c=>c.kind==="settings").length===1')
  assert.deepEqual(await run('window.calls[0].input'), { enabled: false, autoDetect: true, apiKey: 'fixture-ui-key' }, 'testing must not enable prose detection')
  assert.equal(await run('window.calls.filter(c=>c.kind==="test").length'), 0, 'new credential is saved before it is tested')
  await run('window.calls[0].resolve({enabled:false,autoDetect:true,apiKeySet:true})')
  await wait('window.calls.filter(c=>c.kind==="test").length===1')
  assert.equal(await run(testDisabled), true)
  assert.equal(await run("[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='保存并测试').classList.contains('ant-btn-loading')"), true, 'test button shows its own busy state')
  assert.equal(await run("document.querySelector('input[aria-label=\"朱雀 API Key\"]').disabled && document.querySelector('[aria-label=\"启用朱雀检测\"]').disabled"), true, 'settings cannot change during a test')
  await run("window.calls.find(c=>c.kind==='test').resolve({success:true,info:'固定示例连接成功',latency:5})")
  await wait('document.body.textContent.includes("固定示例连接成功") && !'+testDisabled)
  assert.equal(await run("document.querySelector('[aria-label=\"启用朱雀检测\"]').getAttribute('aria-checked')"), 'false')
  assert.equal(await run("document.querySelector('input[aria-label=\"朱雀 API Key\"]').value"), '', 'saved credentials are never echoed into the input')
  await screenshot('disabled-connection-success')
  // The saved credential can be tested again with a blank input, while remaining disabled.
  await click('保存并测试')
  await wait('window.calls.filter(c=>c.kind==="settings").length===2')
  assert.deepEqual(await run('window.calls.filter(c=>c.kind==="settings")[1].input'), { enabled: false, autoDetect: true }, 'blank key preserves the local credential')
  await run('window.calls.filter(c=>c.kind==="settings")[1].resolve({enabled:false,autoDetect:true,apiKeySet:true})')
  await wait('window.calls.filter(c=>c.kind==="test").length===2')
  await run("window.calls.filter(c=>c.kind==='test')[1].resolve({success:false,info:'朱雀密钥无效（401），请重新配置。',latency:8})")
  await wait('document.body.textContent.includes("朱雀密钥无效（401）") && !'+testDisabled)
  await changeKey('replacement-fixture-key')
  await wait('!document.body.textContent.includes("朱雀密钥无效（401）")')
  await changeKey('')
  await run("document.querySelector('[aria-label=\"启用朱雀检测\"]').click()")
  await run("{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='保存配置');b.click();b.click();}")
  await wait('window.calls.filter(c=>c.kind==="settings").length===3')
  assert.deepEqual(await run('window.calls.filter(c=>c.kind==="settings")[2].input'), { enabled: true, autoDetect: true })
  await run('window.calls.filter(c=>c.kind==="settings")[2].resolve({enabled:true,autoDetect:true,apiKeySet:true})')
  await wait('document.body.textContent.includes("朱雀配置已保存")')
  await click('配置朱雀检测')
  await wait("document.querySelector('input[aria-label=\"朱雀 API Key\"]').value===''")
  await click('保存配置')
  await wait('window.calls.filter(c=>c.kind==="settings").length===4')
  assert.deepEqual(await run('window.calls.filter(c=>c.kind==="settings")[3].input'), { enabled: true, autoDetect: true }, 'blank key preserves local credential without echoing it')
  await run('window.calls.filter(c=>c.kind==="settings")[3].resolve({enabled:true,autoDetect:true,apiKeySet:true})')
  await wait('document.body.textContent.includes("朱雀配置已保存")')
  await click('配置朱雀检测')
  await run("document.querySelector('[aria-label=\"清除朱雀密钥\"]').click()")
  await wait(testDisabled)
  assert.equal(await run("document.querySelector('[aria-label=\"启用朱雀检测\"]').disabled && document.querySelector('[aria-label=\"启用朱雀检测\"]').getAttribute('aria-checked')==='false'"), true, 'clearing the key disables prose detection and prevents re-enabling it')
  await click('保存配置')
  await wait('window.calls.filter(c=>c.kind==="settings").length===5')
  assert.deepEqual(await run('window.calls.filter(c=>c.kind==="settings")[4].input'), { enabled: false, autoDetect: true, apiKey: '' })
  await run('window.calls.filter(c=>c.kind==="settings")[4].resolve({enabled:false,autoDetect:true,apiKeySet:false})')
  await wait('document.body.textContent.includes("朱雀配置已保存")')
  await click('配置朱雀检测')
  await wait(testDisabled)
  await changeKey('fixture-unavailable-key')
  await wait('!'+testDisabled)
  await click('保存并测试')
  await wait('window.calls.filter(c=>c.kind==="settings").length===6')
  await run("window.calls.filter(c=>c.kind==='settings')[5].reject(new Error(\"Error invoking remote method 'zhuque:updateSettings': Error: 本机安全存储不可用，未保存密钥。\"))")
  await wait('document.body.textContent.includes("本机安全存储不可用，未保存密钥。") && !'+testDisabled)
  assert.equal(await run('document.body.textContent.includes("Error invoking remote method")'), false)
  assert.equal(await run('document.body.textContent.includes("测试需先启用检测")'), false)
  assert.equal(await run('window.calls.filter(c=>c.kind==="test").length'), 2, 'failed saving never tests an older credential')
  await screenshot('settings-encryption-failure')
  await run('window.showChapter(1)')
  await wait('window.calls.some(c=>c.kind==="read"&&c.id===1)')
  await run("window.calls.find(c=>c.kind==='read'&&c.id===1).resolve({enabled:true,autoDetect:true,apiKeySet:true,status:'not_checked'})")
  await wait('document.querySelector("[data-zhuque-chapter]").textContent.includes("尚未检测")')
  await run("window.editor='有未保存修改。'")
  await click('检测正文')
  await wait('document.body.textContent.includes("尚有未保存修改")')
  assert.equal(await run('window.calls.filter(c=>c.kind==="detect").length'), 0)
  await run("window.editor='已保存的正文。'")
  await run("{const b=[...document.querySelectorAll('button')].find(b=>b.textContent.trim()==='检测正文');b.click();b.click();}")
  await wait('window.calls.filter(c=>c.kind==="detect").length===1')
  await run('window.showChapter(2)')
  await wait('window.calls.some(c=>c.kind==="read"&&c.id===2)')
  await run("window.calls.find(c=>c.kind==='detect').resolve({enabled:true,autoDetect:true,apiKeySet:true,status:'success',report:{metrics:{aiRatio:0.99,suspectedAiRatio:0,humanRatio:0.01,segments:[]}}});window.calls.find(c=>c.kind==='read'&&c.id===2).resolve({enabled:true,autoDetect:true,apiKeySet:true,status:'stale',report:{checkedAt:'2026-10-07T00:00:00Z',metrics:{aiRatio:0.99,suspectedAiRatio:0,humanRatio:0.01,segments:[]}}})")
  await wait('document.body.textContent.includes("旧结果已过期")')
  assert.equal(await run('document.body.textContent.includes("99.0%")'), false, 'old chapter and stale content scores must not be shown as current')
  await click('刷新状态')
  await wait('window.calls.filter(c=>c.kind==="read"&&c.id===2).length===2')
  const currentReport = { chapterId: 2, contentHash: createHash('sha256').update('已保存的正文。').digest('hex'), checkedAt: '2026-10-07T00:00:00Z', status: 'success', metrics: { aiRatio: 0.3, suspectedAiRatio: 0.5, humanRatio: 0.2, segments: [{ label: 2, confidence: 0.8, text: '已保存的正文。' }] } }
  await run('window.calls.filter(c=>c.kind==="read"&&c.id===2)[1].resolve('+JSON.stringify({ enabled: true, autoDetect: true, apiKeySet: true, status: 'success', report: currentReport })+')')
  await wait('document.body.textContent.includes("AI内容 30.0%")')
  assert.equal(await run('document.body.textContent.includes("疑似AI 50.0%") && document.body.textContent.includes("人工内容 20.0%")'), true, 'ratios are separate, not an invented combined AI rate')
  await click('刷新状态')
  await wait('window.calls.filter(c=>c.kind==="read"&&c.id===2).length===3')
  await run('window.calls.filter(c=>c.kind==="read"&&c.id===2)[2].resolve('+JSON.stringify({ enabled: true, autoDetect: true, apiKeySet: true, status: 'running', report: { ...currentReport, contentHash: 'previous-version' } })+')')
  await wait('document.querySelector("[data-zhuque-chapter]").textContent.includes("检测中")')
  assert.equal(await run('document.body.textContent.includes("30.0%")'), false, 'pending detection hides old rates')
  await wait('window.calls.filter(c=>c.kind==="read"&&c.id===2).length===4')
  await run('window.calls.filter(c=>c.kind==="read"&&c.id===2)[3].resolve('+JSON.stringify({ enabled: true, autoDetect: true, apiKeySet: true, status: 'success', report: currentReport })+')')
  await wait('document.body.textContent.includes("AI内容 30.0%")')
  // Exercise the actual author workspace entry, not only the reusable panel.
  await run('window.showManuscript()')
  await wait('!!document.querySelector(".author-manuscript__editor")')
  await click('审校')
  await wait('window.calls.filter(c=>c.kind==="read"&&c.id===1).length===2')
  await run('window.calls.filter(c=>c.kind==="read"&&c.id===1)[1].resolve({enabled:true,autoDetect:true,apiKeySet:true,status:"not_checked"})')
  await wait('!!document.querySelector("[data-zhuque-chapter]") && document.body.textContent.includes("尚未检测")')
  await click('检测正文')
  await wait('window.calls.filter(c=>c.kind==="detect").length===2')
  assert.equal(await run('window.calls.filter(c=>c.kind==="detect")[1].id'), 1)
  assert.equal(await run('window.calls.filter(c=>c.kind==="detect")[1].expectedContent'), '已保存的正文。', 'active manuscript sends its saved version to the CAS guard')
  await run('window.calls.filter(c=>c.kind==="detect")[1].resolve('+JSON.stringify({ enabled: true, autoDetect: true, apiKeySet: true, status: 'success', report: {...currentReport, chapterId:1} })+')')
  await wait('document.body.textContent.includes("AI内容 30.0%")')
  await screenshot('manuscript-review')
  await click('正文')
  await wait('!!document.querySelector(".author-manuscript__editor")')
  await run("{const i=document.querySelector('.author-manuscript__editor');Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value').set.call(i,'修改后的正文。');i.dispatchEvent(new Event('input',{bubbles:true}));}")
  await wait('document.body.textContent.includes("有未保存修改")')
  await click('审校')
  await wait('window.calls.filter(c=>c.kind==="read"&&c.id===1).length===3')
  await run('window.calls.filter(c=>c.kind==="read"&&c.id===1)[2].resolve({enabled:true,autoDetect:true,apiKeySet:true,status:"not_checked"})')
  await wait('document.body.textContent.includes("尚未检测")')
  await click('检测正文')
  await wait('document.body.textContent.includes("尚有未保存修改")')
  assert.equal(await run('window.calls.filter(c=>c.kind==="detect").length'), 2, 'actual manuscript preserves the unsaved-text guard across tabs')
  win.destroy()
  console.log('PASS Zhuque UI: disabled connection testing, save-before-test, key omission/clearing, duplicate submit, busy state, result invalidation, faithful errors, unsaved-text guard, chapter switch, stale scores, separate ratios, polling, and active Manuscript review tab. Actual ReactDOM; fixture API only. Screenshots: '+temp)
}
main().then(() => app.exit(0)).catch(error => { console.error(error); app.exit(1) })
