export {
  GLOBAL_WRITING_RULES,
  expandBackgroundPrompt,
  protagonistPrompt,
  batchCharacterPrompt,
  regenerateCharacterPrompt,
  characterRelationsPrompt,
  mapGenerationPrompt,
  storyArcsPrompt,
  chapterOutlinePrompt,
  chapterWritingPrompt,
  chapterSummaryPrompt,
  aiCheckPrompt,
  rewriteParagraphPrompt,
  genericExpandPrompt,
  subplotExpandPrompt,
  contentScoringPrompt,
} from '../../src/shared/prompt-library'
